Repository sopt-makers/sopt-crew-backend, pull requests merged in 2023-12, with the labels that each got.

#90 [#88] env: [Spring] 패키지간 import 문제 해결
  main/src/main/java/org/sopt/makers/crew/main/entity/comment/Comment.java
  main/src/main/java/org/sopt/makers/crew/main/entity/post/Post.java
  main/src/main/java/org/sopt/makers/crew/main/entity/report/Report.java
  main/src/main/java/org/sopt/makers/crew/main/entity/user/User.java
Labels: size/M

#92 [#91] feat: [모임] 전체 모임의 게시글을 조회하도록 변경 및 모임 정보도 함께 추가
  server/src/post/v1/dto/get-meeting-posts/post-v1-get-posts-query.dto.ts
  server/src/post/v1/dto/get-meeting-posts/post-v1-get-posts-response-post.dto.ts
  server/src/post/v1/post-v1.service.ts
Labels: feature, size/M

#97 [#96] fix: 모임 이미지 필드명 통일
  main/src/main/java/org/sopt/makers/crew/main/user/v2/dto/response/UserV2GetAllMeetingByUserMeetingDto.java
Labels: bug, size/XS

#98 [#95] add : 모임의 정보중 모임 소개 데이터 필드 추가
  server/src/post/v1/dto/get-meeting-post/post-v1-get-post-response.dto.ts
  server/src/post/v1/post-v1.service.ts
Labels: feature, size/XS

#100 [#99] fix: CORS 관련 config 추가
  main/src/main/java/org/sopt/makers/crew/main/common/config/WebMvcConfig.java
Labels: bug, size/S

#108 [#107] env: spring Prod 환경변수 추가
  main/src/main/resources/application-prod.yml
Labels: environment, size/M
