Repository sopt-makers/sopt-crew-backend, pull requests merged in 2023-09, with the labels that each got.

#40 [#37] 피드 기능 구현
  server/src/app.module.ts
  server/src/comment/comment.module.ts
  server/src/comment/v1/comment-v1.controller.ts
  server/src/comment/v1/comment-v1.module.ts
  server/src/comment/v1/comment-v1.service.ts
  server/src/comment/v1/dto/create-comment/comment-v1-create-comment-body.dto.ts
  server/src/comment/v1/dto/create-comment/comment-v1-create-comment-response.dto.ts
  server/src/comment/v1/dto/get-comments/comment-v1-get-comments-query.dto.ts
  server/src/comment/v1/dto/get-comments/comment-v1-get-comments-response.dto.ts
  server/src/comment/v1/dto/report-comment/comment-v1-report-comment-param.dto.ts
  server/src/comment/v1/dto/report-comment/comment-v1-report-comment-response.dto.ts
  server/src/comment/v1/dto/switch-comment-like/comment-v1-switch-comment-like-param.dto.ts
  server/src/comment/v1/dto/switch-comment-like/comment-v1-switch-comment-like-response.dto.ts
  server/src/entity/apply/apply.entity.ts
  server/src/entity/comment/comment.entity.ts
  server/src/entity/comment/comment.repository.ts
  server/src/entity/like/like.entity.ts
  server/src/entity/like/like.repository.ts
  server/src/entity/meeting/meeting.entity.ts
  server/src/entity/post/post.entity.ts
  server/src/entity/post/post.repository.ts
  server/src/entity/report/report.entity.ts
  server/src/entity/report/report.repository.ts
  server/src/entity/user/user.entity.ts
  server/src/post/post.module.ts
  server/src/post/v1/dto/create-meeting-post/post-v1-create-post-body.dto.ts
  server/src/post/v1/dto/create-meeting-post/post-v1-create-post-response.dto.ts
  server/src/post/v1/dto/get-meeting-post-count/post-v1-get-post-count-query.dto.ts
  server/src/post/v1/dto/get-meeting-post-count/post-v1-get-post-count-response.dto.ts
  server/src/post/v1/dto/get-meeting-post/post-v1-get-post-response.dto.ts
  server/src/post/v1/dto/get-meeting-posts/post-v1-get-posts-query.dto.ts
  server/src/post/v1/dto/get-meeting-posts/post-v1-get-posts-response-post.dto.ts
  server/src/post/v1/dto/get-meeting-posts/post-v1-get-posts-response.dto.ts
  server/src/post/v1/dto/report-post/post-v1-report-post-param.dto.ts
  server/src/post/v1/dto/report-post/post-v1-report-post-response.dto.ts
  server/src/post/v1/dto/switch-post-like/post-v1-switch-post-like-param.dto.ts
  server/src/post/v1/dto/switch-post-like/post-v1-switch-post-like-response.dto.ts
  server/src/post/v1/post-v1.controller.ts
  server/src/post/v1/post-v1.module.ts
  server/src/post/v1/post-v1.service.ts
  server/test/unit/post/v1/post-v1.service.test.ts
Labels: feature, size/XXL

#48 [#47] feat: 미팅 조회시 생성 기수별로 가능하도록 수정
  server/src/entity/meeting/meeting.entity.ts
  server/src/entity/meeting/meeting.repository.ts
  server/src/meeting/v0/dto/get-all-meetings/meeting-v0-get-all-meetings-query.dto.ts
  server/src/meeting/v0/dto/meeting-v0-get-meeting-by-id-response.dto.ts
  server/src/meeting/v0/meeting-v0.service.ts
  server/src/meeting/v1/meeting-v1.service.ts
Labels: feature, size/M

#50 [#49] env: typeorm force sync 부분 변경
  server/src/app.module.ts
Labels: environment, size/XS

#54 [#53] 모임 상세 조회 시, approved 필드 값 구하는 로직 수정
  server/src/meeting/v0/meeting-v0.service.ts
Labels: bug, size/S

#55 [#43] docs: 성공 응답모델 문서에 CommonResponseDto 적용
  server/src/comment/v1/comment-v1.controller.ts
  server/src/common/decorator/api-ok-response-common.decorator.ts
  server/src/common/dto/common-response.dto.ts
  server/src/common/interceptor/transform.interceptor.ts
  server/src/common/utils/swagger.ts
  server/src/meeting/v0/meeting-v0.controller.ts
  server/src/meeting/v1/meeting-v1.controller.ts
  server/src/notice/v1/notice-v1.controller.ts
  server/src/post/v1/post-v1.controller.ts
  server/src/user/v0/dto/get-apply-by-user/user-v0-get-apply-by-user-apply-meeting.dto.ts
  server/src/user/v0/dto/get-apply-by-user/user-v0-get-apply-by-user-apply.dto.ts
  server/src/user/v0/dto/get-apply-by-user/user-v0-get-apply-by-user.dto.ts
  server/src/user/v0/dto/get-meeting-by-user/user-v0-get-meeting-by-user-meeting.dto.ts
  server/src/user/v0/dto/get-meeting-by-user/user-v0-get-meeting-by-user.dto.ts
  server/src/user/v0/user-v0.controller.ts
  server/src/user/v0/user-v0.service.ts
  server/src/user/v1/user-v1.controller.ts
Labels: documentation, size/L

#46 [#45] 신청한 모임 최신순으로 정렬
  server/src/user/v0/user-v0.service.ts
Labels: bug, size/XS

#61 [#57] 조회 api의 response에서 null 대신 빈 배열로 처리
  server/src/comment/v1/comment-v1.controller.ts
  server/src/comment/v1/comment-v1.service.ts
  server/src/meeting/v0/meeting-v0.controller.ts
  server/src/meeting/v0/meeting-v0.service.ts
  server/src/meeting/v1/meeting-v1.controller.ts
  server/src/meeting/v1/meeting-v1.service.ts
  server/src/post/v1/post-v1.service.ts
Labels: feature, size/S

#63 [#62] 댓글 및 피드 조회 api의 response에 유저 orgId 추가
  server/src/comment/v1/comment-v1.service.ts
  server/src/comment/v1/dto/get-comments/comment-v1-get-comments-response.dto.ts
  server/src/post/v1/dto/get-meeting-post/post-v1-get-post-response.dto.ts
  server/src/post/v1/dto/get-meeting-posts/post-v1-get-posts-response-post.dto.ts
  server/src/post/v1/post-v1.service.ts
Labels: feature, size/S
