Repository sopt-makers/sopt-crew-backend, pull requests merged in 2023-10, with the labels that each got.

#65 [#64] 피드 댓글 작성자 프로필 이미지 및 개수 전체 개수를 내려주도록 수정
  server/src/post/v1/post-v1.service.ts
Labels: bug

#69 [#67] 사용하지 않는 콘솔로그를 삭제했습니다
  server/src/post/v1/post-v1.service.ts
Labels: size/XS

#76 [#75] 모임 게시글 삭제시 해당 정보만 삭제하도록 변경
  server/src/meeting/v0/meeting-v0.controller.ts
  server/src/meeting/v1/meeting-v1.controller.ts
  server/src/post/v1/post-v1.service.ts
Labels: bug, size/S

#79 [#78] 내가 만든 모임 최신순 정렬
  server/src/entity/meeting/meeting.repository.ts
Labels: bug, size/XS

#81 모임 지원자 Export 하는 csv 파일에 참여자의 파트 정보 컬럼 추가
  server/src/meeting/v1/meeting-v1.service.ts
Labels: feature, size/S

#83 [#82] v0.5.3
  server/package-lock.json
  server/package.json
  server/src/common/utils/swagger.ts
Labels: size/XS, deployment
