Repository sopt-makers/sopt-crew-backend, pull requests merged in 2024-12, with the labels that each got.

#480 refactor: redis를 활용한 조회 성능 최적화
  docker-compose.yml
  main/build.gradle
  main/src/main/java/org/sopt/makers/crew/main/auth/v2/service/AuthV2ServiceImpl.java
  main/src/main/java/org/sopt/makers/crew/main/entity/apply/Apply.java
  main/src/main/java/org/sopt/makers/crew/main/entity/common/BaseTimeEntity.java
  main/src/main/java/org/sopt/makers/crew/main/entity/meeting/CoLeader.java
  main/src/main/java/org/sopt/makers/crew/main/entity/meeting/CoLeaderReader.java
  main/src/main/java/org/sopt/makers/crew/main/entity/meeting/CoLeaderRepository.java
  main/src/main/java/org/sopt/makers/crew/main/entity/meeting/CoLeaders.java
  main/src/main/java/org/sopt/makers/crew/main/entity/meeting/Meeting.java
  main/src/main/java/org/sopt/makers/crew/main/entity/meeting/MeetingReader.java
  main/src/main/java/org/sopt/makers/crew/main/entity/meeting/vo/ImageUrlVO.java
  main/src/main/java/org/sopt/makers/crew/main/entity/user/User.java
  main/src/main/java/org/sopt/makers/crew/main/entity/user/UserReader.java
  main/src/main/java/org/sopt/makers/crew/main/entity/user/vo/UserActivityVO.java
  main/src/main/java/org/sopt/makers/crew/main/external/redis/RedisConfig.java
  main/src/main/java/org/sopt/makers/crew/main/external/redis/RedisProperties.java
  main/src/main/java/org/sopt/makers/crew/main/global/advice/ControllerExceptionAdvice.java
  main/src/main/java/org/sopt/makers/crew/main/global/aop/ExecutionLoggingAop.java
  main/src/main/java/org/sopt/makers/crew/main/global/constant/PropertiesConfiguration.java
  main/src/main/java/org/sopt/makers/crew/main/global/dto/MeetingCreatorDto.java
  main/src/main/java/org/sopt/makers/crew/main/global/dto/MeetingResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/global/exception/ErrorStatus.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/redis/CoLeaderRedisDto.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/redis/CoLeadersRedisDto.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/redis/MeetingRedisDto.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/response/MeetingV2GetMeetingBannerResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/response/MeetingV2GetMeetingByIdResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceImpl.java
  main/src/main/java/org/sopt/makers/crew/main/user/v2/dto/response/MeetingV2GetCreatedMeetingByUserResponseDto.java
  main/src/main/resources/application-dev.yml
  main/src/main/resources/application-local.yml
  main/src/main/resources/application-prod.yml
  main/src/main/resources/application-test.yml
  main/src/test/java/org/sopt/makers/crew/main/entity/user/UserActivityVOTest.java
  main/src/test/java/org/sopt/makers/crew/main/entity/user/UserEntityTest.java
  main/src/test/java/org/sopt/makers/crew/main/external/redisContainerBaseTest.java
  main/src/test/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceTest.java
  main/src/test/java/org/sopt/makers/crew/main/user/v2/UserServiceTest.java
Labels: 🛠️ refactor, size/XXL

#500 v2.3.0
  docker-compose.yml
  main/build.gradle
  main/src/main/java/org/sopt/makers/crew/main/auth/v2/service/AuthV2ServiceImpl.java
  main/src/main/java/org/sopt/makers/crew/main/entity/apply/Apply.java
  main/src/main/java/org/sopt/makers/crew/main/entity/common/BaseTimeEntity.java
  main/src/main/java/org/sopt/makers/crew/main/entity/meeting/CoLeader.java
  main/src/main/java/org/sopt/makers/crew/main/entity/meeting/CoLeaderReader.java
  main/src/main/java/org/sopt/makers/crew/main/entity/meeting/CoLeaderRepository.java
  main/src/main/java/org/sopt/makers/crew/main/entity/meeting/CoLeaders.java
  main/src/main/java/org/sopt/makers/crew/main/entity/meeting/Meeting.java
  main/src/main/java/org/sopt/makers/crew/main/entity/meeting/MeetingReader.java
  main/src/main/java/org/sopt/makers/crew/main/entity/meeting/vo/ImageUrlVO.java
  main/src/main/java/org/sopt/makers/crew/main/entity/user/User.java
  main/src/main/java/org/sopt/makers/crew/main/entity/user/UserReader.java
  main/src/main/java/org/sopt/makers/crew/main/entity/user/vo/UserActivityVO.java
  main/src/main/java/org/sopt/makers/crew/main/external/redis/RedisConfig.java
  main/src/main/java/org/sopt/makers/crew/main/external/redis/RedisProperties.java
  main/src/main/java/org/sopt/makers/crew/main/global/advice/ControllerExceptionAdvice.java
  main/src/main/java/org/sopt/makers/crew/main/global/aop/ExecutionLoggingAop.java
  main/src/main/java/org/sopt/makers/crew/main/global/config/SecurityConfig.java
  main/src/main/java/org/sopt/makers/crew/main/global/constant/PropertiesConfiguration.java
  main/src/main/java/org/sopt/makers/crew/main/global/dto/MeetingCreatorDto.java
  main/src/main/java/org/sopt/makers/crew/main/global/dto/MeetingResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/global/exception/ErrorStatus.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/redis/CoLeaderRedisDto.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/redis/CoLeadersRedisDto.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/redis/MeetingRedisDto.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/response/MeetingV2GetMeetingBannerResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/response/MeetingV2GetMeetingByIdResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceImpl.java
  main/src/main/java/org/sopt/makers/crew/main/user/v2/dto/response/MeetingV2GetCreatedMeetingByUserResponseDto.java
  main/src/main/resources/application-dev.yml
  main/src/main/resources/application-local.yml
  main/src/main/resources/application-prod.yml
  main/src/main/resources/application-test.yml
  main/src/test/java/org/sopt/makers/crew/main/entity/user/UserActivityVOTest.java
  main/src/test/java/org/sopt/makers/crew/main/entity/user/UserEntityTest.java
  main/src/test/java/org/sopt/makers/crew/main/external/redisContainerBaseTest.java
  main/src/test/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceTest.java
  main/src/test/java/org/sopt/makers/crew/main/user/v2/UserServiceTest.java
Labels: size/XXL, 🚀 deployment, 2️⃣ minor

#504 fix: 메이커스 리드 임시조치
  main/src/main/java/org/sopt/makers/crew/main/entity/user/User.java
  main/src/main/java/org/sopt/makers/crew/main/entity/user/enums/UserPart.java
Labels: 🐞 fix, size/M

#505 v2.3.1
  main/src/main/java/org/sopt/makers/crew/main/entity/user/User.java
  main/src/main/java/org/sopt/makers/crew/main/entity/user/enums/UserPart.java
Labels: size/M, 🚀 deployment, 3️⃣ patch

#502 chore: 번개 -> 번쩍으로 변경
  main/src/main/java/org/sopt/makers/crew/main/entity/meeting/enums/MeetingCategory.java
  main/src/main/java/org/sopt/makers/crew/main/entity/user/enums/UserPart.java
Labels: size/M, 🪛 chore

#511 refactor: prometheus actuator 경로 화이트리스트에 추가 완료
  main/src/main/java/org/sopt/makers/crew/main/global/config/SecurityConfig.java
Labels: 🛠️ refactor, size/XS

#512 v2.3.2
  main/src/main/java/org/sopt/makers/crew/main/entity/meeting/enums/MeetingCategory.java
  main/src/main/java/org/sopt/makers/crew/main/entity/user/enums/UserPart.java
  main/src/main/java/org/sopt/makers/crew/main/global/config/SecurityConfig.java
Labels: size/M, 🚀 deployment, 3️⃣ patch

#518 del: 배포 관련 파일인 docker-compose.yml과 deploy.sh 스크립트 제거 완료
  deploy-dev.sh
  deploy-prod.sh
  docker-compose.dev.yml
  docker-compose.local.yml
  docker-compose.prod.yml
  docker-compose.yml
Labels: size/XL, ␡ del
