Repository sopt-makers/sopt-crew-backend, pull requests merged in 2024-10, with the labels that each got.

#433 fix: 모임 전체 조회 로직 수정 & 모임 전체 조회 테스트 일부 작성
  main/src/main/java/org/sopt/makers/crew/main/entity/user/vo/UserActivityVO.java
  main/src/main/java/org/sopt/makers/crew/main/global/dto/MeetingResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceImpl.java
  main/src/main/resources/schema.sql
  main/src/test/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceTest.java
  main/src/test/resources/sql/meeting-service-test-data.sql
Labels: 🐞 fix, size/L, 🧪 test

#434 v2.1.4
  main/src/main/java/org/sopt/makers/crew/main/entity/user/vo/UserActivityVO.java
  main/src/main/java/org/sopt/makers/crew/main/global/dto/MeetingResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceImpl.java
  main/src/main/resources/schema.sql
  main/src/test/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceTest.java
  main/src/test/resources/sql/meeting-service-test-data.sql
Labels: size/L, 🚀 deployment, 3️⃣ patch

#436 fix: 모임상세조회 스웨거 명시 오류 해결
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/response/MeetingV2GetMeetingByIdResponseDto.java
Labels: 🐞 fix, size/XS

#438 v2.1.4
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/response/MeetingV2GetMeetingByIdResponseDto.java
Labels: size/XS, 🚀 deployment, 3️⃣ patch

#439 test: 지원자/참여자 조회 API 테스트 코드 작성
  main/src/test/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceTest.java
Labels: size/L, 🧪 test

#444 fix: excel로 열었을 때, csv 한글 깨짐 이슈 해결
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceImpl.java
Labels: 🐞 fix, size/S

#441 test: 모임상세조회 및 모임전체조회 테스트 코드 작성
  main/src/main/java/org/sopt/makers/crew/main/entity/meeting/MeetingSearchRepositoryImpl.java
  main/src/test/java/org/sopt/makers/crew/main/global/util/StubTime.java
  main/src/test/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceTest.java
  main/src/test/resources/sql/meeting-service-test-data.sql
Labels: size/XL, 🧪 test

#442 test: 모임 지원 취소, 모임 지원 테스트 코드 작성
  main/src/test/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceTest.java
Labels: size/L, 🧪 test

#446 v2.1.5
  main/src/main/java/org/sopt/makers/crew/main/entity/meeting/MeetingSearchRepositoryImpl.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceImpl.java
  main/src/test/java/org/sopt/makers/crew/main/global/util/StubTime.java
  main/src/test/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceTest.java
  main/src/test/resources/sql/meeting-service-test-data.sql
Labels: size/XXL, 🚀 deployment, 3️⃣ patch

#451 chore: likeCount Notnull 추가
  main/src/main/java/org/sopt/makers/crew/main/post/v2/dto/response/PostDetailBaseDto.java
Labels: size/XS, 🪛 chore

#452 v2.1.6
  main/src/main/java/org/sopt/makers/crew/main/post/v2/dto/response/PostDetailBaseDto.java
Labels: size/XS, 🚀 deployment, 3️⃣ patch

#454 fix: 조회수 증가 로직 오류 해결
  main/src/main/java/org/sopt/makers/crew/main/entity/post/Post.java
  main/src/main/java/org/sopt/makers/crew/main/post/v2/service/PostV2ServiceImpl.java
Labels: 🐞 fix, size/S

#459 v2.1.6
  main/src/main/java/org/sopt/makers/crew/main/entity/post/Post.java
  main/src/main/java/org/sopt/makers/crew/main/post/v2/service/PostV2ServiceImpl.java
Labels: size/S, 🚀 deployment, 3️⃣ patch

#448 feat: 전체 사용자 조회 API 구현
  main/src/main/java/org/sopt/makers/crew/main/user/v2/UserV2Api.java
  main/src/main/java/org/sopt/makers/crew/main/user/v2/UserV2Controller.java
  main/src/main/java/org/sopt/makers/crew/main/user/v2/dto/response/UserV2GetAllUserDto.java
  main/src/main/java/org/sopt/makers/crew/main/user/v2/service/UserV2Service.java
  main/src/main/java/org/sopt/makers/crew/main/user/v2/service/UserV2ServiceImpl.java
Labels: 🎁 feature, size/L

#449 feat: 공동 모임장 구현
  main/src/main/java/org/sopt/makers/crew/main/entity/meeting/CoLeader.java
  main/src/main/java/org/sopt/makers/crew/main/entity/meeting/CoLeaderRepository.java
  main/src/main/java/org/sopt/makers/crew/main/entity/meeting/CoLeaders.java
  main/src/main/java/org/sopt/makers/crew/main/entity/user/UserRepository.java
  main/src/main/java/org/sopt/makers/crew/main/global/exception/ErrorStatus.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/request/MeetingV2CreateMeetingBodyDto.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/response/MeetingV2CoLeaderResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/response/MeetingV2GetMeetingByIdResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceImpl.java
  main/src/main/java/org/sopt/makers/crew/main/user/v2/dto/response/MeetingV2GetCreatedMeetingByUserResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/user/v2/service/UserV2ServiceImpl.java
  main/src/main/resources/schema.sql
  main/src/test/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceTest.java
Labels: 🎁 feature, size/L

#430 feat: 로그 출력용 AOP 구현
  main/src/main/java/org/sopt/makers/crew/main/global/aop/ExecutionLoggingAop.java
Labels: 🎁 feature, size/L

#464 refactor: 승인된 신청자 수 필드 추가
  main/src/main/java/org/sopt/makers/crew/main/global/dto/MeetingResponseDto.java
  main/src/test/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceTest.java
Labels: 🛠️ refactor, size/M

#466 chore: approvedCount 필드 추가
  main/src/main/java/org/sopt/makers/crew/main/user/v2/dto/response/MeetingV2GetCreatedMeetingByUserResponseDto.java
Labels: size/S, 🪛 chore

#470 fix: 모임 수정 오류 해결
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceImpl.java
  main/src/test/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceTest.java
Labels: 🐞 fix, size/M
