Repository sopt-makers/sopt-crew-backend, pull requests merged in 2024-11, with the labels that each got.

#476 fix: 모임장은 공동모임장이 될 수 없다.
  main/src/main/java/org/sopt/makers/crew/main/entity/meeting/CoLeader.java
  main/src/main/java/org/sopt/makers/crew/main/global/exception/ErrorStatus.java
  main/src/test/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceTest.java
Labels: 🐞 fix, size/M

#486 feat: APP BE 와의 통신을 위한 모임 목록 조회 API 개발
  main/src/main/java/org/sopt/makers/crew/main/comment/v2/service/CommentV2ServiceImpl.java
  main/src/main/java/org/sopt/makers/crew/main/entity/meeting/Meeting.java
  main/src/main/java/org/sopt/makers/crew/main/entity/meeting/enums/EnMeetingStatus.java
  main/src/main/java/org/sopt/makers/crew/main/external/notification/PushNotificationEnums.java
  main/src/main/java/org/sopt/makers/crew/main/external/notification/PushNotificationServerClient.java
  main/src/main/java/org/sopt/makers/crew/main/external/notification/PushNotificationService.java
  main/src/main/java/org/sopt/makers/crew/main/external/notification/dto/PushNotificationRequestDto.java
  main/src/main/java/org/sopt/makers/crew/main/external/notification/dto/PushNotificationResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/external/playground/service/MemberBlockService.java
  main/src/main/java/org/sopt/makers/crew/main/external/playground/service/MemberBlockServiceImpl.java
  main/src/main/java/org/sopt/makers/crew/main/global/config/SecurityConfig.java
  main/src/main/java/org/sopt/makers/crew/main/global/dto/MeetingResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/global/pagination/dto/PageOptionsDto.java
  main/src/main/java/org/sopt/makers/crew/main/global/util/AdvertisementCustomPageable.java
  main/src/main/java/org/sopt/makers/crew/main/global/util/CustomPageable.java
  main/src/main/java/org/sopt/makers/crew/main/internal/InternalMeetingApi.java
  main/src/main/java/org/sopt/makers/crew/main/internal/InternalMeetingController.java
  main/src/main/java/org/sopt/makers/crew/main/internal/dto/InternalMeetingGetAllMeetingDto.java
  main/src/main/java/org/sopt/makers/crew/main/internal/dto/InternalMeetingGetAllMeetingQueryDto.java
  main/src/main/java/org/sopt/makers/crew/main/internal/dto/InternalMeetingResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/internal/dto/UserOrgIdRequestDto.java
  main/src/main/java/org/sopt/makers/crew/main/internal/service/InternalMeetingService.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/response/MeetingV2GetMeetingBannerResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/response/MeetingV2GetMeetingByIdResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceImpl.java
  main/src/main/java/org/sopt/makers/crew/main/post/v2/service/PostV2ServiceImpl.java
  main/src/main/java/org/sopt/makers/crew/main/user/v2/dto/response/MeetingV2GetCreatedMeetingByUserResponseDto.java
  main/src/test/java/org/sopt/makers/crew/main/entity/meeting/MeetingTest.java
Labels: 🎁 feature, size/L

#491 chore: category 필드 추가
  main/src/main/java/org/sopt/makers/crew/main/internal/dto/InternalMeetingResponseDto.java
Labels: size/S, 🪛 chore

#489 feat: app be를 위한 스터디 수 조회 API 구현
  main/src/main/java/org/sopt/makers/crew/main/entity/apply/ApplyRepository.java
  main/src/main/java/org/sopt/makers/crew/main/internal/InternalMeetingStatsApi.java
  main/src/main/java/org/sopt/makers/crew/main/internal/InternalMeetingStatsController.java
  main/src/main/java/org/sopt/makers/crew/main/internal/dto/ApprovedStudyCountResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/internal/service/InternalMeetingStatsService.java
Labels: 🎁 feature, size/L

#496 fix: 검증 로직 일부 수정
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceImpl.java
Labels: 🐞 fix, size/XS
