Repository sopt-makers/sopt-crew-backend, pull requests merged in 2024-09, with the labels that each got.

#355 hotfix: 댓글 조회 수정
  main/src/main/java/org/sopt/makers/crew/main/comment/v2/service/CommentV2ServiceImpl.java
  main/src/main/java/org/sopt/makers/crew/main/entity/comment/CommentRepository.java
Labels: size/XS

#359 chore: 유저관련 temp API 추가
  main/src/main/java/org/sopt/makers/crew/main/comment/v2/CommentV2Api.java
  main/src/main/java/org/sopt/makers/crew/main/comment/v2/CommentV2Controller.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/MeetingV2Api.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/MeetingV2Controller.java
  main/src/main/java/org/sopt/makers/crew/main/user/v2/UserV2Api.java
  main/src/main/java/org/sopt/makers/crew/main/user/v2/UserV2Controller.java
Labels: size/L, 🪛 chore

#361 chore: 모임 관련 API 스웨거에 보이는 응답값 수정
  main/src/main/java/org/sopt/makers/crew/main/common/dto/MeetingResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/query/MeetingV2GetAllMeetingQueryDto.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/response/MeetingV2GetMeetingByIdResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/user/v2/dto/response/ApplyV2GetAppliedMeetingByUserResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/user/v2/dto/response/MeetingV2GetCreatedMeetingByUserResponseDto.java
Labels: 📚 documentation, size/M, 🪛 chore

#357 feat: 모니터링 서버 구축
  main/build.gradle
  main/src/main/java/org/sopt/makers/crew/main/common/config/SecurityConfig.java
  main/src/main/resources/application-dev.yml
  main/src/main/resources/application-prod.yml
  main/src/main/resources/application-test.yml
Labels: 🎁 feature, 🏭 environment, size/L

#365 chore: 광고 조회 API 데이터 추가
  main/src/main/java/org/sopt/makers/crew/main/advertisement/dto/AdvertisementGetDto.java
Labels: size/S, 🪛 chore

#363 refactor: 시큐리티 config 코드 개선 및 헬스 체크 방식 변경
  main/src/main/java/org/sopt/makers/crew/main/common/config/SecurityConfig.java
  main/src/main/java/org/sopt/makers/crew/main/health/v1/HealthController.java
  main/src/main/java/org/sopt/makers/crew/main/health/v1/HealthService.java
  main/src/main/java/org/sopt/makers/crew/main/health/v1/dtos/service/get_health/response/HealthServiceGetHealthResponseDataDto.java
  main/src/main/java/org/sopt/makers/crew/main/health/v1/dtos/service/get_health/response/HealthServiceGetHealthResponseDataInfoDto.java
  main/src/main/java/org/sopt/makers/crew/main/health/v1/dtos/service/get_health/response/HealthServiceGetHealthResponseDataStatusDto.java
  main/src/main/java/org/sopt/makers/crew/main/health/v1/dtos/service/get_health/response/HealthServiceGetHealthResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/health/v1/enums/EnHealthV1ServiceType.java
Labels: 🛠️ refactor, size/L

#374 fix: AppliedCount -> ApprovedCount 로 변경
  main/src/main/java/org/sopt/makers/crew/main/entity/apply/Applies.java
  main/src/main/java/org/sopt/makers/crew/main/user/v2/service/UserV2ServiceImpl.java
Labels: 🐞 fix, size/XS

#375 feat: application-local.yml 구현
  main/src/main/resources/application-local.yml
Labels: 🎁 feature, size/M, 🪄 setting

#378 fix(Post): desc 데이터 추가
  main/src/main/java/org/sopt/makers/crew/main/entity/post/PostSearchRepositoryImpl.java
  main/src/main/java/org/sopt/makers/crew/main/post/v2/dto/response/PostMeetingDto.java
Labels: 🐞 fix, size/L

#376 chore: 플그 db 연결 작업
  main/src/main/java/org/sopt/makers/crew/main/common/config/CrewDatabaseConfig.java
  main/src/main/java/org/sopt/makers/crew/main/common/config/PlaygroundDataSourceConfig.java
  main/src/main/java/org/sopt/makers/crew/main/external/playground/TestService.java
  main/src/main/java/org/sopt/makers/crew/main/external/playground/entity/member_block/MemberBlock.java
  main/src/main/java/org/sopt/makers/crew/main/external/playground/entity/member_block/MemberBlockRepository.java
  main/src/main/resources/application-dev.yml
  main/src/main/resources/application-local.yml
  main/src/main/resources/application-prod.yml
Labels: size/L, 🪛 chore

#380 refactor: docker hub 푸시할 때 태그 추가
  .github/workflows/cd-dev.yml
  .github/workflows/cd-prod.yml
Labels: 🛠️ refactor, size/S

#384 hotfix: 컬럼 이름 변경
  main/src/main/java/org/sopt/makers/crew/main/external/playground/entity/member_block/MemberBlock.java
Labels: size/XS

#385 hotfix: 컬럼 이름 변경 (#384)
  main/src/main/java/org/sopt/makers/crew/main/external/playground/entity/member_block/MemberBlock.java
Labels: size/XS

#386 hotfix: playground와 엔티티 싱크 맞추기
  main/src/main/java/org/sopt/makers/crew/main/external/playground/entity/member_block/MemberBlock.java
Labels: size/S

#387 feat: 피드(post) 차단 기능 구축
  main/build.gradle
  main/src/main/java/org/sopt/makers/crew/main/common/config/CrewDatabaseConfig.java
  main/src/main/java/org/sopt/makers/crew/main/common/config/JpaAuditingConfig.java
  main/src/main/java/org/sopt/makers/crew/main/common/config/PlaygroundDataSourceConfig.java
  main/src/main/java/org/sopt/makers/crew/main/entity/post/PostSearchRepository.java
  main/src/main/java/org/sopt/makers/crew/main/entity/post/PostSearchRepositoryImpl.java
  main/src/main/java/org/sopt/makers/crew/main/external/playground/entity/member_block/MemberBlockRepository.java
  main/src/main/java/org/sopt/makers/crew/main/external/playground/service/MemberBlockService.java
  main/src/main/java/org/sopt/makers/crew/main/external/playground/service/MemberBlockServiceImpl.java
  main/src/main/java/org/sopt/makers/crew/main/post/v2/PostV2Api.java
  main/src/main/java/org/sopt/makers/crew/main/post/v2/PostV2Controller.java
  main/src/main/java/org/sopt/makers/crew/main/post/v2/dto/response/PostDetailBaseDto.java
  main/src/main/java/org/sopt/makers/crew/main/post/v2/dto/response/PostDetailResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/post/v2/dto/response/PostDetailWithBlockStatusResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/post/v2/dto/response/PostV2GetPostsResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/post/v2/service/PostV2Service.java
  main/src/main/java/org/sopt/makers/crew/main/post/v2/service/PostV2ServiceImpl.java
  main/src/main/java/org/sopt/makers/crew/main/user/v2/service/UserV2Service.java
  main/src/main/java/org/sopt/makers/crew/main/user/v2/service/UserV2ServiceImpl.java
  main/src/main/resources/application-test.yml
  main/src/main/resources/schema.sql
  main/src/test/java/org/sopt/makers/crew/main/entity/user/UserRepositoryTest.java
  main/src/test/java/org/sopt/makers/crew/main/meeting/v2/repository/ApplyRepositoryTest.java
  main/src/test/java/org/sopt/makers/crew/main/post/v2/repository/PostRepositoryTest.java
  main/src/test/resources/sql/apply-repository-test-data.sql
  main/src/test/resources/sql/delete-all-data.sql
  main/src/test/resources/sql/post-repository-test-data.sql
Labels: 🎁 feature, size/XXL

#388 refactor: 피드(post) 차단 기능 FE 의견 반영
  main/build.gradle
  main/src/main/java/org/sopt/makers/crew/main/common/config/CrewDatabaseConfig.java
  main/src/main/java/org/sopt/makers/crew/main/common/config/JpaAuditingConfig.java
  main/src/main/java/org/sopt/makers/crew/main/common/config/PlaygroundDataSourceConfig.java
  main/src/main/java/org/sopt/makers/crew/main/entity/post/PostSearchRepository.java
  main/src/main/java/org/sopt/makers/crew/main/entity/post/PostSearchRepositoryImpl.java
  main/src/main/java/org/sopt/makers/crew/main/external/playground/entity/member_block/MemberBlockRepository.java
  main/src/main/java/org/sopt/makers/crew/main/external/playground/service/MemberBlockService.java
  main/src/main/java/org/sopt/makers/crew/main/external/playground/service/MemberBlockServiceImpl.java
  main/src/main/java/org/sopt/makers/crew/main/post/v2/PostV2Api.java
  main/src/main/java/org/sopt/makers/crew/main/post/v2/PostV2Controller.java
  main/src/main/java/org/sopt/makers/crew/main/post/v2/dto/response/PostDetailBaseDto.java
  main/src/main/java/org/sopt/makers/crew/main/post/v2/dto/response/PostDetailResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/post/v2/dto/response/PostV2GetPostsResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/post/v2/service/PostV2Service.java
  main/src/main/java/org/sopt/makers/crew/main/post/v2/service/PostV2ServiceImpl.java
  main/src/main/java/org/sopt/makers/crew/main/user/v2/service/UserV2Service.java
  main/src/main/java/org/sopt/makers/crew/main/user/v2/service/UserV2ServiceImpl.java
  main/src/main/resources/application-test.yml
  main/src/main/resources/schema.sql
  main/src/test/java/org/sopt/makers/crew/main/entity/user/UserRepositoryTest.java
  main/src/test/java/org/sopt/makers/crew/main/meeting/v2/repository/ApplyRepositoryTest.java
  main/src/test/java/org/sopt/makers/crew/main/post/v2/repository/PostRepositoryTest.java
  main/src/test/resources/sql/apply-repository-test-data.sql
  main/src/test/resources/sql/delete-all-data.sql
  main/src/test/resources/sql/post-repository-test-data.sql
Labels: 🛠️ refactor, size/XXL

#392 feat: 댓글 조회에서 차단된 유저 필터링 구현
  main/src/main/java/org/sopt/makers/crew/main/comment/v2/dto/response/CommentDto.java
  main/src/main/java/org/sopt/makers/crew/main/comment/v2/dto/response/ReplyDto.java
  main/src/main/java/org/sopt/makers/crew/main/comment/v2/service/CommentV2ServiceImpl.java
  main/src/main/java/org/sopt/makers/crew/main/external/playground/TestService.java
  main/src/main/java/org/sopt/makers/crew/main/external/playground/service/MemberBlockService.java
  main/src/main/java/org/sopt/makers/crew/main/external/playground/service/MemberBlockServiceImpl.java
Labels: 🎁 feature, size/M

#390 fix: 모임 상세 조회 API 오류 수정
  main/src/main/java/org/sopt/makers/crew/main/entity/apply/Applies.java
Labels: 🐞 fix, size/S

#394 fix: 신청 정보없는 경우에 대한 처리
  main/src/main/java/org/sopt/makers/crew/main/entity/apply/Applies.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceImpl.java
Labels: 🐞 fix, size/S

#397 chore: 현재 기수 35기로 수정
  main/src/main/java/org/sopt/makers/crew/main/common/constant/CrewConst.java
  server/src/common/constant/active-generation.const.ts
Labels: size/S, 🪛 chore

#398 fix: isBlockedPost를 Lombok getter에서 생략 후 직접 getter 구현
  main/src/main/java/org/sopt/makers/crew/main/post/v2/dto/response/PostDetailResponseDto.java
Labels: 🐞 fix, size/XS

#400 refactor: isBlockedComment를 Lombok getter에서 생략 후 직접 getter 구현
  main/src/main/java/org/sopt/makers/crew/main/comment/v2/dto/response/CommentDto.java
  main/src/main/java/org/sopt/makers/crew/main/comment/v2/dto/response/ReplyDto.java
Labels: 🛠️ refactor, size/M

#402 v2.1.0
  main/build.gradle
  main/src/main/java/org/sopt/makers/crew/main/comment/v2/dto/response/CommentDto.java
  main/src/main/java/org/sopt/makers/crew/main/comment/v2/dto/response/ReplyDto.java
  main/src/main/java/org/sopt/makers/crew/main/comment/v2/service/CommentV2ServiceImpl.java
  main/src/main/java/org/sopt/makers/crew/main/common/config/CrewDatabaseConfig.java
  main/src/main/java/org/sopt/makers/crew/main/common/config/JpaAuditingConfig.java
  main/src/main/java/org/sopt/makers/crew/main/common/config/PlaygroundDataSourceConfig.java
  main/src/main/java/org/sopt/makers/crew/main/common/constant/CrewConst.java
  main/src/main/java/org/sopt/makers/crew/main/entity/apply/Applies.java
  main/src/main/java/org/sopt/makers/crew/main/entity/post/PostSearchRepository.java
  main/src/main/java/org/sopt/makers/crew/main/entity/post/PostSearchRepositoryImpl.java
  main/src/main/java/org/sopt/makers/crew/main/external/playground/TestService.java
  main/src/main/java/org/sopt/makers/crew/main/external/playground/entity/member_block/MemberBlockRepository.java
  main/src/main/java/org/sopt/makers/crew/main/external/playground/service/MemberBlockService.java
  main/src/main/java/org/sopt/makers/crew/main/external/playground/service/MemberBlockServiceImpl.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceImpl.java
  main/src/main/java/org/sopt/makers/crew/main/post/v2/PostV2Api.java
  main/src/main/java/org/sopt/makers/crew/main/post/v2/PostV2Controller.java
  main/src/main/java/org/sopt/makers/crew/main/post/v2/dto/response/PostDetailBaseDto.java
  main/src/main/java/org/sopt/makers/crew/main/post/v2/dto/response/PostDetailResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/post/v2/dto/response/PostV2GetPostsResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/post/v2/service/PostV2Service.java
  main/src/main/java/org/sopt/makers/crew/main/post/v2/service/PostV2ServiceImpl.java
  main/src/main/java/org/sopt/makers/crew/main/user/v2/service/UserV2Service.java
  main/src/main/java/org/sopt/makers/crew/main/user/v2/service/UserV2ServiceImpl.java
  main/src/main/resources/application-test.yml
  main/src/main/resources/schema.sql
  main/src/test/java/org/sopt/makers/crew/main/entity/user/UserRepositoryTest.java
  main/src/test/java/org/sopt/makers/crew/main/meeting/v2/repository/ApplyRepositoryTest.java
  main/src/test/java/org/sopt/makers/crew/main/post/v2/repository/PostRepositoryTest.java
  main/src/test/resources/sql/apply-repository-test-data.sql
  main/src/test/resources/sql/delete-all-data.sql
  main/src/test/resources/sql/post-repository-test-data.sql
  server/src/common/constant/active-generation.const.ts
Labels: size/XXL, 🚀 deployment, 2️⃣ minor

#370 refactor: pinpoint 적용
  main/Dockerfile
Labels: 🛠️ refactor, size/XS

#404 chore: docker 파일 수정
  .github/workflows/cd-dev.yml
  .github/workflows/cd-prod.yml
  main/Dockerfile
Labels: size/S, 🪛 chore

#406 feat: 모니터링 관련 사항 롤백
  .github/workflows/cd-dev.yml
  .github/workflows/cd-prod.yml
  main/Dockerfile
Labels: 🎁 feature, size/S

#408 fix: 모니터링 관련 수정
  .github/workflows/cd-dev.yml
Labels: 🐞 fix, size/XS

#413 v2.1.1
  .github/workflows/cd-dev.yml
  .github/workflows/cd-prod.yml
  main/Dockerfile
Labels: size/S, 🚀 deployment, 3️⃣ patch

#410 fix: 광고 구좌 조회 로직 개선
  main/src/main/java/org/sopt/makers/crew/main/advertisement/dto/AdvertisementGetDto.java
  main/src/main/java/org/sopt/makers/crew/main/advertisement/dto/AdvertisementsGetResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/advertisement/service/AdvertisementService.java
  main/src/main/java/org/sopt/makers/crew/main/entity/advertisement/Advertisement.java
  main/src/main/java/org/sopt/makers/crew/main/entity/advertisement/AdvertisementRepository.java
  main/src/main/java/org/sopt/makers/crew/main/entity/advertisement/enums/AdvertisementCategory.java
Labels: 🐞 fix, size/L

#414 chore: 모임 생성, 수정 v2 API 유효성 검사 수정
  main/src/main/java/org/sopt/makers/crew/main/common/config/CrewDatabaseConfig.java
  main/src/main/java/org/sopt/makers/crew/main/common/config/PlaygroundDataSourceConfig.java
  main/src/main/java/org/sopt/makers/crew/main/entity/meeting/Meeting.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/MeetingV2Api.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/MeetingV2Controller.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/request/MeetingV2CreateMeetingBodyDto.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/response/MeetingV2GetMeetingByIdResponseDto.java
  main/src/main/resources/schema.sql
  main/src/test/java/org/sopt/makers/crew/main/meeting/v2/repository/MeetingRepositoryTest.java
  main/src/test/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2MockServiceTest.java
  main/src/test/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceTest.java
  main/src/test/resources/sql/apply-repository-test-data.sql
  main/src/test/resources/sql/post-repository-test-data.sql
Labels: size/XXL

#419 refactor: 광고 구좌 조회 응답 DTO에서 isSponsoredContent 필드 제거
  main/src/main/java/org/sopt/makers/crew/main/advertisement/dto/AdvertisementsGetResponseDto.java
Labels: 🛠️ refactor, size/S

#424 chore: 테스트 환경 개선
  main/build.gradle
  main/src/main/resources/application-test.yml
  main/src/main/resources/logback-spring.xml
Labels: size/S, 🪛 chore

#426 fix: 회원가입 시 user 객체를 생성한 후 orgId에 접근할 수 있도록 수정
  server/src/auth/v0/auth-v0.service.ts
Labels: 🐞 fix, size/L

#428 v2.1.3
  main/build.gradle
  main/src/main/resources/application-test.yml
  main/src/main/resources/logback-spring.xml
  server/src/auth/v0/auth-v0.service.ts
Labels: size/L, 🚀 deployment, 3️⃣ patch
