Repository sopt-makers/sopt-crew-backend, pull requests merged in 2024-04, with the labels that each got.

#148 [FEAT] 모임 게시글 댓글 작성 API 마이그레이션 및 알림 작업
  docker-compose.yml
  main/src/main/java/org/sopt/makers/crew/main/comment/v2/CommentV2Controller.java
  main/src/main/java/org/sopt/makers/crew/main/comment/v2/dto/request/CommentV2CreateCommentBodyDto.java
  main/src/main/java/org/sopt/makers/crew/main/comment/v2/dto/response/CommentV2CreateCommentResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/comment/v2/service/CommentV2Service.java
  main/src/main/java/org/sopt/makers/crew/main/comment/v2/service/CommentV2ServiceImpl.java
  main/src/main/java/org/sopt/makers/crew/main/common/response/ErrorStatus.java
  main/src/main/java/org/sopt/makers/crew/main/entity/comment/Comment.java
  main/src/main/java/org/sopt/makers/crew/main/entity/comment/CommentRepository.java
  main/src/main/java/org/sopt/makers/crew/main/entity/post/Post.java
  main/src/main/java/org/sopt/makers/crew/main/entity/post/PostRepository.java
  main/src/main/java/org/sopt/makers/crew/main/internal/notification/PushNotificationEnums.java
  server/src/comment/v1/comment-v1.controller.ts
Labels: size/L

#154 [#153] feat: 모임 둘러보기 API 응답에 모임 모집시작시간 추가
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/response/MeetingV2GetMeetingBannerResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceImpl.java
Labels: feature

#158 [#157] fix: 모임 홈 개선 - 모임 둘러보기 API 응답 모임 모집기간 수정
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/response/MeetingV2GetMeetingBannerResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceImpl.java
Labels: size/XS

#160 [FIX] 테스트 코드 오류 수정
  main/src/test/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceTest.java
Labels: bug, size/XS

#164 [FIX] Dockerfile 로 이미지 빌드할 때 테스트 코드 실행안하도록 수정
  main/Dockerfile
Labels: environment, size/XS

#166 [FEAT] 인터셉터 활용한 로깅 구현
  main/build.gradle
  main/src/main/java/org/sopt/makers/crew/main/MainApplication.java
  main/src/main/java/org/sopt/makers/crew/main/common/aop/ExecutionLoggingAop.java
  main/src/main/resources/console-appender.xml
  main/src/main/resources/logback-spring.xml
Labels: feature, size/L

#172 [FIX] 익명 유저 처리를 위한 수정
  main/src/main/java/org/sopt/makers/crew/main/common/aop/ExecutionLoggingAop.java
Labels: bug, size/XS

#170 [FEAT] 모임생성 API 마이그레이션
  main/build.gradle
  main/src/main/java/org/sopt/makers/crew/main/common/constant/CrewConst.java
  main/src/main/java/org/sopt/makers/crew/main/common/response/ErrorStatus.java
  main/src/main/java/org/sopt/makers/crew/main/entity/meeting/enums/MeetingCategory.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/MeetingV2Api.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/MeetingV2Controller.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/MeetingMapper.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/request/MeetingV2CreateMeetingBodyDto.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/response/MeetingV2CreateMeetingResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2Service.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceImpl.java
  server/src/entity/meeting/enum/meeting-category.enum.ts
Labels: feature, size/XL
