Repository sopt-makers/sopt-crew-backend, pull requests merged in 2024-08, with the labels that each got.

#277 [DOCS] 스웨거 문서 작성
  main/src/main/java/org/sopt/makers/crew/main/comment/v2/dto/query/CommentV2GetCommentsQueryDto.java
  main/src/main/java/org/sopt/makers/crew/main/comment/v2/dto/request/CommentV2CreateCommentBodyDto.java
  main/src/main/java/org/sopt/makers/crew/main/comment/v2/dto/request/CommentV2MentionUserInCommentRequestDto.java
  main/src/main/java/org/sopt/makers/crew/main/comment/v2/dto/response/CommentDto.java
  main/src/main/java/org/sopt/makers/crew/main/comment/v2/dto/response/CommentV2CreateCommentResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/comment/v2/dto/response/CommentV2GetCommentsResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/comment/v2/dto/response/CommentV2ReportCommentResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/comment/v2/dto/response/CommentV2UpdateCommentResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/comment/v2/dto/response/CommentWriterDto.java
  main/src/main/java/org/sopt/makers/crew/main/comment/v2/service/CommentV2ServiceImpl.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/request/MeetingV2CreateMeetingBodyDto.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/response/ApplicantDto.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/response/ApplyInfoDto.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/response/MeetingGetApplyListResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/response/MeetingV2ApplyMeetingResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/response/MeetingV2CreateMeetingResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/response/MeetingV2GetAllMeetingByOrgUserDto.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/response/MeetingV2GetAllMeetingByOrgUserMeetingDto.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/response/MeetingV2GetMeetingBannerResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/response/MeetingV2GetMeetingBannerResponseUserDto.java
  main/src/main/java/org/sopt/makers/crew/main/post/v2/dto/query/PostGetPostsCommand.java
  main/src/main/java/org/sopt/makers/crew/main/post/v2/dto/response/PostDetailBaseDto.java
  main/src/main/java/org/sopt/makers/crew/main/post/v2/dto/response/PostDetailResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/post/v2/dto/response/PostMeetingDto.java
  main/src/main/java/org/sopt/makers/crew/main/post/v2/dto/response/PostV2CreatePostResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/post/v2/dto/response/PostV2GetPostsResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/post/v2/dto/response/PostWriterInfoDto.java
  main/src/main/java/org/sopt/makers/crew/main/user/v2/dto/response/UserV2GetAllMeetingByUserMeetingDto.java
  main/src/main/java/org/sopt/makers/crew/main/user/v2/dto/response/UserV2GetAllMentionUserDto.java
Labels: documentation, size/L

#283 [fix] 스웨거 문서 수정
  main/src/main/java/org/sopt/makers/crew/main/comment/v2/CommentV2Api.java
  main/src/main/java/org/sopt/makers/crew/main/comment/v2/CommentV2Controller.java
Labels: bug, size/S

#285 fix: 좋아요 여부 로직 수정
  main/src/main/java/org/sopt/makers/crew/main/comment/v2/service/CommentV2ServiceImpl.java
  main/src/main/java/org/sopt/makers/crew/main/entity/like/LikeRepository.java
Labels: bug, size/XS

#287 feat: 임시 API 개발
  main/src/main/java/org/sopt/makers/crew/main/comment/v2/CommentV2Api.java
  main/src/main/java/org/sopt/makers/crew/main/comment/v2/CommentV2Controller.java
  main/src/main/java/org/sopt/makers/crew/main/common/dto/TempResponseDto.java
Labels: feature, size/M

#279 [FEAT] 모임 게시글 삭제 V2 API 구현
  main/src/main/java/org/sopt/makers/crew/main/entity/comment/CommentRepository.java
  main/src/main/java/org/sopt/makers/crew/main/entity/like/LikeRepository.java
  main/src/main/java/org/sopt/makers/crew/main/entity/post/Post.java
  main/src/main/java/org/sopt/makers/crew/main/entity/post/PostSearchRepositoryImpl.java
  main/src/main/java/org/sopt/makers/crew/main/post/v2/PostV2Api.java
  main/src/main/java/org/sopt/makers/crew/main/post/v2/PostV2Controller.java
  main/src/main/java/org/sopt/makers/crew/main/post/v2/service/PostV2Service.java
  main/src/main/java/org/sopt/makers/crew/main/post/v2/service/PostV2ServiceImpl.java
  server/src/post/v1/post-v1.controller.ts
Labels: feature, size/M

#290 [CHORE] 페이지네이션 메타데이터 추가
  main/src/main/java/org/sopt/makers/crew/main/comment/v2/CommentV2Controller.java
  main/src/main/java/org/sopt/makers/crew/main/comment/v2/dto/response/CommentV2GetCommentsResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/comment/v2/service/CommentV2ServiceImpl.java
  server/src/notice/v1/notice-v1.controller.ts
Labels: size/S, chore

#288 [FEAT] 게시글 댓글 좋아요 토글 V2 API 구현
  main/src/main/java/org/sopt/makers/crew/main/comment/v2/CommentV2Api.java
  main/src/main/java/org/sopt/makers/crew/main/comment/v2/CommentV2Controller.java
  main/src/main/java/org/sopt/makers/crew/main/comment/v2/dto/response/CommentV2SwitchCommentLikeResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/comment/v2/service/CommentV2Service.java
  main/src/main/java/org/sopt/makers/crew/main/comment/v2/service/CommentV2ServiceImpl.java
  main/src/main/java/org/sopt/makers/crew/main/entity/comment/Comment.java
  main/src/main/java/org/sopt/makers/crew/main/entity/like/Like.java
  main/src/main/java/org/sopt/makers/crew/main/entity/like/LikeRepository.java
  server/src/comment/v1/comment-v1.controller.ts
Labels: size/L

#292 [FIX] 댓글 삭제 후 조회 로직 오류 해결
  main/src/main/java/org/sopt/makers/crew/main/comment/v2/dto/response/CommentDto.java
  main/src/main/java/org/sopt/makers/crew/main/entity/comment/Comment.java
Labels: bug, size/S

#294 fix: PUT 메서드 추가
  main/src/main/java/org/sopt/makers/crew/main/common/config/SecurityConfig.java
Labels: bug, size/XS

#297 [fix] 스웨거 오류 해결
  main/src/main/java/org/sopt/makers/crew/main/comment/v2/CommentV2Api.java
  main/src/main/java/org/sopt/makers/crew/main/comment/v2/CommentV2Controller.java
Labels: bug, size/M

#299 fix: 스웨거 오류 해결
  main/src/main/java/org/sopt/makers/crew/main/comment/v2/dto/response/CommentV2GetCommentsResponseDto.java
Labels: size/XS, chore

#302 [FEAT] 광고 조회 API 개발
  docker-compose.yml
  main/src/main/java/org/sopt/makers/crew/main/advertisement/AdvertisementApi.java
  main/src/main/java/org/sopt/makers/crew/main/advertisement/AdvertisementController.java
  main/src/main/java/org/sopt/makers/crew/main/advertisement/dto/AdvertisementGetResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/advertisement/service/AdvertisementService.java
  main/src/main/java/org/sopt/makers/crew/main/entity/advertisement/Advertisement.java
  main/src/main/java/org/sopt/makers/crew/main/entity/advertisement/AdvertisementRepository.java
Labels: feature, size/L

#304 [CHORE] 업데이트 -> 생성시점으로 변경
  main/src/main/java/org/sopt/makers/crew/main/comment/v2/dto/request/CommentV2MentionUserInCommentRequestDto.java
  main/src/main/java/org/sopt/makers/crew/main/comment/v2/dto/response/CommentDto.java
  main/src/main/java/org/sopt/makers/crew/main/comment/v2/dto/response/CommentWriterDto.java
  main/src/main/java/org/sopt/makers/crew/main/comment/v2/dto/response/ReplyDto.java
  main/src/main/java/org/sopt/makers/crew/main/comment/v2/service/CommentV2ServiceImpl.java
  main/src/main/java/org/sopt/makers/crew/main/post/v2/dto/request/PostV2MentionUserInPostRequestDto.java
  main/src/main/java/org/sopt/makers/crew/main/post/v2/service/PostV2ServiceImpl.java
  main/src/main/java/org/sopt/makers/crew/main/user/v2/dto/response/UserV2GetAllMentionUserDto.java
Labels: size/M, chore

#306 [CHORE] FE 요청에 맞게 수정
  main/src/main/java/org/sopt/makers/crew/main/advertisement/AdvertisementApi.java
  main/src/main/java/org/sopt/makers/crew/main/advertisement/AdvertisementController.java
  main/src/main/java/org/sopt/makers/crew/main/advertisement/dto/AdvertisementGetResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/advertisement/service/AdvertisementService.java
  main/src/main/java/org/sopt/makers/crew/main/comment/v2/dto/query/CommentV2GetCommentsQueryDto.java
  main/src/main/java/org/sopt/makers/crew/main/comment/v2/dto/request/CommentV2CreateCommentBodyDto.java
  main/src/main/java/org/sopt/makers/crew/main/comment/v2/dto/request/CommentV2MentionUserInCommentRequestDto.java
  main/src/main/java/org/sopt/makers/crew/main/comment/v2/dto/request/CommentV2UpdateCommentBodyDto.java
  main/src/main/java/org/sopt/makers/crew/main/comment/v2/dto/response/CommentDto.java
  main/src/main/java/org/sopt/makers/crew/main/comment/v2/dto/response/CommentV2CreateCommentResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/comment/v2/dto/response/CommentV2GetCommentsResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/comment/v2/dto/response/CommentV2ReportCommentResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/comment/v2/dto/response/CommentV2SwitchCommentLikeResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/comment/v2/dto/response/CommentV2UpdateCommentResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/comment/v2/dto/response/CommentWriterDto.java
  main/src/main/java/org/sopt/makers/crew/main/comment/v2/dto/response/ReplyDto.java
  main/src/main/java/org/sopt/makers/crew/main/common/dto/TempResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/common/pagination/dto/PageMetaDto.java
  main/src/main/java/org/sopt/makers/crew/main/entity/advertisement/Advertisement.java
  main/src/main/java/org/sopt/makers/crew/main/entity/advertisement/AdvertisementRepository.java
  main/src/main/java/org/sopt/makers/crew/main/entity/advertisement/enums/AdvertisementCategory.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/request/MeetingV2CreateMeetingBodyDto.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/response/ApplicantDto.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/response/ApplyInfoDto.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/response/MeetingGetApplyListResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/response/MeetingV2ApplyMeetingResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/response/MeetingV2CreateMeetingResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/response/MeetingV2GetAllMeetingByOrgUserDto.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/response/MeetingV2GetAllMeetingByOrgUserMeetingDto.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/response/MeetingV2GetMeetingBannerResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/response/MeetingV2GetMeetingBannerResponseUserDto.java
  main/src/main/java/org/sopt/makers/crew/main/notice/dto/request/NoticeV2CreateRequestDto.java
  main/src/main/java/org/sopt/makers/crew/main/notice/dto/response/NoticeV2GetResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/post/v2/dto/request/PostV2CreatePostBodyDto.java
  main/src/main/java/org/sopt/makers/crew/main/post/v2/dto/request/PostV2MentionUserInPostRequestDto.java
  main/src/main/java/org/sopt/makers/crew/main/post/v2/dto/response/CommenterThumbnails.java
  main/src/main/java/org/sopt/makers/crew/main/post/v2/dto/response/PostDetailBaseDto.java
  main/src/main/java/org/sopt/makers/crew/main/post/v2/dto/response/PostDetailResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/post/v2/dto/response/PostMeetingDto.java
  main/src/main/java/org/sopt/makers/crew/main/post/v2/dto/response/PostV2CreatePostResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/post/v2/dto/response/PostV2GetPostCountResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/post/v2/dto/response/PostV2GetPostsResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/post/v2/dto/response/PostWriterInfoDto.java
  main/src/main/java/org/sopt/makers/crew/main/user/v2/dto/response/UserV2GetAllMeetingByUserMeetingDto.java
  main/src/main/java/org/sopt/makers/crew/main/user/v2/dto/response/UserV2GetAllMentionUserDto.java
Labels: size/XL, chore

#308 [FEAT] 유저 관련 API 마이그레이션
  main/src/main/java/org/sopt/makers/crew/main/common/config/SecurityConfig.java
  main/src/main/java/org/sopt/makers/crew/main/common/dto/MeetingCreatorDto.java
  main/src/main/java/org/sopt/makers/crew/main/common/jwt/JwtAuthenticationEntryPoint.java
  main/src/main/java/org/sopt/makers/crew/main/common/jwt/JwtAuthenticationFilter.java
  main/src/main/java/org/sopt/makers/crew/main/common/jwt/JwtExceptionType.java
  main/src/main/java/org/sopt/makers/crew/main/common/jwt/JwtTokenProvider.java
  main/src/main/java/org/sopt/makers/crew/main/common/jwt/UserAuthentication.java
  main/src/main/java/org/sopt/makers/crew/main/entity/apply/Applies.java
  main/src/main/java/org/sopt/makers/crew/main/entity/apply/ApplyRepository.java
  main/src/main/java/org/sopt/makers/crew/main/entity/meeting/MeetingRepository.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/request/MeetingV2CreateMeetingBodyDto.java
  main/src/main/java/org/sopt/makers/crew/main/user/v2/UserApi.java
  main/src/main/java/org/sopt/makers/crew/main/user/v2/UserV2Api.java
  main/src/main/java/org/sopt/makers/crew/main/user/v2/UserV2Controller.java
  main/src/main/java/org/sopt/makers/crew/main/user/v2/dto/response/ApplyV2GetAppliedMeetingByUserResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/user/v2/dto/response/MeetingV2GetCreatedMeetingByUserResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/user/v2/dto/response/UserV2GetAppliedMeetingByUserResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/user/v2/dto/response/UserV2GetCreatedMeetingByUserResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/user/v2/dto/response/UserV2GetUserOwnProfileResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/user/v2/service/UserV2Service.java
  main/src/main/java/org/sopt/makers/crew/main/user/v2/service/UserV2ServiceImpl.java
Labels: feature, size/L

#310 feat: 전체모임 검색 및 필터링 마이그레이션
  main/src/main/java/org/sopt/makers/crew/main/common/dto/MeetingCreatorDto.java
  main/src/main/java/org/sopt/makers/crew/main/common/dto/MeetingResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/entity/meeting/MeetingRepository.java
  main/src/main/java/org/sopt/makers/crew/main/entity/meeting/MeetingSearchRepository.java
  main/src/main/java/org/sopt/makers/crew/main/entity/meeting/MeetingSearchRepositoryImpl.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/MeetingV2Api.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/MeetingV2Controller.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/query/MeetingV2GetAllMeetingQueryDto.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/response/MeetingV2GetAllMeetingDto.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2Service.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceImpl.java
  main/src/main/java/org/sopt/makers/crew/main/user/v2/dto/response/MeetingV2GetCreatedMeetingByUserResponseDto.java
  server/src/meeting/v0/meeting-v0.controller.ts
Labels: feature, size/L

#311 [FEAT] 로그인/회원가입 마이그레이션
  .github/workflows/cd-dev.yml
  .github/workflows/cd-prod.yml
  .github/workflows/ci.yml
  docker-compose.yml
  main/src/main/java/org/sopt/makers/crew/main/MainApplication.java
  main/src/main/java/org/sopt/makers/crew/main/auth/v2/AuthV2Api.java
  main/src/main/java/org/sopt/makers/crew/main/auth/v2/AuthV2Controller.java
  main/src/main/java/org/sopt/makers/crew/main/auth/v2/dto/request/AuthV2RequestDto.java
  main/src/main/java/org/sopt/makers/crew/main/auth/v2/dto/response/AuthV2ResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/auth/v2/service/AuthV2Service.java
  main/src/main/java/org/sopt/makers/crew/main/auth/v2/service/AuthV2ServiceImpl.java
  main/src/main/java/org/sopt/makers/crew/main/common/config/FeignClientConfig.java
  main/src/main/java/org/sopt/makers/crew/main/common/config/SecurityConfig.java
  main/src/main/java/org/sopt/makers/crew/main/common/jwt/JwtAuthenticationEntryPoint.java
  main/src/main/java/org/sopt/makers/crew/main/common/jwt/JwtAuthenticationFilter.java
  main/src/main/java/org/sopt/makers/crew/main/common/jwt/JwtExceptionType.java
  main/src/main/java/org/sopt/makers/crew/main/common/jwt/JwtTokenProvider.java
  main/src/main/java/org/sopt/makers/crew/main/common/jwt/UserAuthentication.java
  main/src/main/java/org/sopt/makers/crew/main/common/response/ErrorStatus.java
  main/src/main/java/org/sopt/makers/crew/main/entity/user/User.java
  main/src/main/java/org/sopt/makers/crew/main/entity/user/UserRepository.java
  main/src/main/java/org/sopt/makers/crew/main/external/playground/PlaygroundServer.java
  main/src/main/java/org/sopt/makers/crew/main/external/playground/PlaygroundService.java
  main/src/main/java/org/sopt/makers/crew/main/external/playground/dto/request/PlaygroundUserRequestDto.java
  main/src/main/java/org/sopt/makers/crew/main/external/playground/dto/response/PlaygroundUserActivityResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/external/playground/dto/response/PlaygroundUserResponseDto.java
  main/src/main/resources/application-dev.yml
  main/src/main/resources/application-prod.yml
  main/src/main/resources/application-test.yml
  server/src/auth/v0/auth-v0.controller.ts
Labels: feature, size/XL

#313 [FEAT] 모임 삭제 API 구현
  main/src/main/java/org/sopt/makers/crew/main/comment/v2/service/CommentV2ServiceImpl.java
  main/src/main/java/org/sopt/makers/crew/main/common/advice/ControllerExceptionAdvice.java
  main/src/main/java/org/sopt/makers/crew/main/common/exception/CommonResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/common/exception/ErrorStatus.java
  main/src/main/java/org/sopt/makers/crew/main/common/jwt/JwtAuthenticationFilter.java
  main/src/main/java/org/sopt/makers/crew/main/entity/apply/ApplyRepository.java
  main/src/main/java/org/sopt/makers/crew/main/entity/comment/Comment.java
  main/src/main/java/org/sopt/makers/crew/main/entity/comment/CommentRepository.java
  main/src/main/java/org/sopt/makers/crew/main/entity/like/LikeRepository.java
  main/src/main/java/org/sopt/makers/crew/main/entity/meeting/Meeting.java
  main/src/main/java/org/sopt/makers/crew/main/entity/meeting/MeetingRepository.java
  main/src/main/java/org/sopt/makers/crew/main/entity/post/Post.java
  main/src/main/java/org/sopt/makers/crew/main/entity/post/PostRepository.java
  main/src/main/java/org/sopt/makers/crew/main/entity/post/PostSearchRepositoryImpl.java
  main/src/main/java/org/sopt/makers/crew/main/entity/user/User.java
  main/src/main/java/org/sopt/makers/crew/main/entity/user/UserRepository.java
  main/src/main/java/org/sopt/makers/crew/main/internal/notification/PushNotificationService.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/MeetingV2Api.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/MeetingV2Controller.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2Service.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceImpl.java
  main/src/main/java/org/sopt/makers/crew/main/notice/service/NoticeV2Service.java
  main/src/main/java/org/sopt/makers/crew/main/post/v2/service/PostV2ServiceImpl.java
  main/src/test/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceTest.java
  server/src/meeting/v0/meeting-v0.controller.ts
Labels: feature, size/L

#315 [CHORE] deprecated 처리
  server/src/meeting/v0/meeting-v0.controller.ts
Labels: size/XS, chore

#317 [FEAT] 모임 수정 API 마이그레이션
  main/src/main/java/org/sopt/makers/crew/main/entity/meeting/Meeting.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/MeetingV2Api.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/MeetingV2Controller.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/request/MeetingV2CreateMeetingBodyDto.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2Service.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceImpl.java
  main/src/test/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceTest.java
  server/src/meeting/v1/meeting-v1.controller.ts
Labels: feature, size/L

#323 [CHORE] 광고 조회 API 수정
  main/src/main/java/org/sopt/makers/crew/main/advertisement/dto/AdvertisementGetResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/advertisement/dto/AdvertisementImageDto.java
  main/src/main/java/org/sopt/makers/crew/main/advertisement/service/AdvertisementService.java
  main/src/main/java/org/sopt/makers/crew/main/entity/advertisement/AdvertisementImage.java
  main/src/main/java/org/sopt/makers/crew/main/entity/advertisement/AdvertisementImageRepository.java
Labels: feature, size/L

#324 [FEAT] presignedUrl 생성 로직 구현
  main/build.gradle
  main/src/main/java/org/sopt/makers/crew/main/common/exception/ErrorStatus.java
  main/src/main/java/org/sopt/makers/crew/main/external/s3/config/AwsProperties.java
  main/src/main/java/org/sopt/makers/crew/main/external/s3/config/AwsPropertiesConfiguration.java
  main/src/main/java/org/sopt/makers/crew/main/external/s3/config/S3Config.java
  main/src/main/java/org/sopt/makers/crew/main/external/s3/service/S3Service.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/MeetingV2Api.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/MeetingV2Controller.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/response/AppliesCsvFileUrlResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/response/PreSignedUrlFieldResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/response/PreSignedUrlResponseDto.java
  main/src/main/resources/application-dev.yml
  main/src/main/resources/application-prod.yml
  main/src/main/resources/application-test.yml
  server/src/meeting/v1/meeting-v1.controller.ts
Labels: feature, size/L

#325 [FEAT] csv 파일 업로드 및 url 반환 로직 구현
  main/build.gradle
  main/src/main/java/org/sopt/makers/crew/main/common/exception/ErrorStatus.java
  main/src/main/java/org/sopt/makers/crew/main/entity/apply/ApplyRepository.java
  main/src/main/java/org/sopt/makers/crew/main/external/s3/config/AwsProperties.java
  main/src/main/java/org/sopt/makers/crew/main/external/s3/service/S3Service.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/MeetingV2Api.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/MeetingV2Controller.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/response/AppliesCsvFileUrlResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/response/PreSignedUrlFieldResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/response/PreSignedUrlResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2Service.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceImpl.java
  main/src/main/resources/application-dev.yml
  main/src/main/resources/application-prod.yml
  main/src/main/resources/application-test.yml
  server/src/meeting/v1/meeting-v1.controller.ts
Labels: feature, size/L

#326 [FEAT] 모임 상세 조회 API 마이그레이션
  main/src/main/java/org/sopt/makers/crew/main/common/constant/CrewConst.java
  main/src/main/java/org/sopt/makers/crew/main/common/dto/MeetingCreatorDto.java
  main/src/main/java/org/sopt/makers/crew/main/common/dto/MeetingResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/entity/apply/Applies.java
  main/src/main/java/org/sopt/makers/crew/main/entity/apply/Apply.java
  main/src/main/java/org/sopt/makers/crew/main/entity/apply/ApplySearchRepositoryImpl.java
  main/src/main/java/org/sopt/makers/crew/main/entity/meeting/Meeting.java
  main/src/main/java/org/sopt/makers/crew/main/entity/user/vo/UserActivityVO.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/MeetingV2Api.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/MeetingV2Controller.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/response/ApplicantByMeetingDto.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/response/ApplyWholeInfoDto.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/response/MeetingV2GetMeetingByIdResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2Service.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceImpl.java
  main/src/main/java/org/sopt/makers/crew/main/user/v2/dto/response/MeetingV2GetCreatedMeetingByUserResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/user/v2/service/UserV2ServiceImpl.java
  main/src/test/java/org/sopt/makers/crew/main/entity/apply/AppliesTest.java
  main/src/test/java/org/sopt/makers/crew/main/entity/meeting/MeetingTest.java
  server/src/meeting/v0/meeting-v0.controller.ts
Labels: feature, size/XL

#327 [FEAT] 모임 게시글 수정 V2 API 구현
  main/.gitignore
  main/src/main/java/org/sopt/makers/crew/main/common/exception/ErrorStatus.java
  main/src/main/java/org/sopt/makers/crew/main/entity/post/Post.java
  main/src/main/java/org/sopt/makers/crew/main/post/v2/PostV2Api.java
  main/src/main/java/org/sopt/makers/crew/main/post/v2/PostV2Controller.java
  main/src/main/java/org/sopt/makers/crew/main/post/v2/dto/request/PostV2UpdatePostBodyDto.java
  main/src/main/java/org/sopt/makers/crew/main/post/v2/dto/response/PostV2UpdatePostResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/post/v2/service/PostV2Service.java
  main/src/main/java/org/sopt/makers/crew/main/post/v2/service/PostV2ServiceImpl.java
  main/src/test/java/org/sopt/makers/crew/main/comment/v2/service/CommentV2ServiceTest.java
  main/src/test/java/org/sopt/makers/crew/main/post/v2/service/PostV2ServiceTest.java
  server/src/post/v1/post-v1.controller.ts
Labels: feature, size/XL

#330 [CHORE] csv 파일 다운로드 로직 수정
  main/src/main/java/org/sopt/makers/crew/main/entity/apply/enums/EnApplyStatus.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/MeetingV2Api.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/MeetingV2Controller.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/query/MeetingGetAppliesCsvQueryDto.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceImpl.java
Labels: feature, size/L

#331 [DOCS] 스웨거 기존과 동일하게 수정
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/MeetingV2Api.java
Labels: size/XS, chore

#335 refactor: 예외 응답 개선
  main/src/main/java/org/sopt/makers/crew/main/common/advice/ControllerExceptionAdvice.java
  main/src/main/java/org/sopt/makers/crew/main/common/exception/ErrorStatus.java
  main/src/main/java/org/sopt/makers/crew/main/common/exception/ExceptionResponse.java
  main/src/main/java/org/sopt/makers/crew/main/common/jwt/JwtAuthenticationEntryPoint.java
Labels: 🛠️ refactor, size/L

#336 [FEAT] 게시글 좋아요 토글 및 게시글 신고 API V2 구현
  main/src/main/java/org/sopt/makers/crew/main/comment/v2/service/CommentV2ServiceImpl.java
  main/src/main/java/org/sopt/makers/crew/main/common/exception/ErrorStatus.java
  main/src/main/java/org/sopt/makers/crew/main/entity/like/Like.java
  main/src/main/java/org/sopt/makers/crew/main/entity/like/LikeRepository.java
  main/src/main/java/org/sopt/makers/crew/main/entity/post/Post.java
  main/src/main/java/org/sopt/makers/crew/main/entity/report/Report.java
  main/src/main/java/org/sopt/makers/crew/main/entity/report/ReportRepository.java
  main/src/main/java/org/sopt/makers/crew/main/post/v2/PostV2Api.java
  main/src/main/java/org/sopt/makers/crew/main/post/v2/PostV2Controller.java
  main/src/main/java/org/sopt/makers/crew/main/post/v2/dto/response/PostV2ReportResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/post/v2/dto/response/PostV2SwitchPostLikeResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/post/v2/service/PostV2Service.java
  main/src/main/java/org/sopt/makers/crew/main/post/v2/service/PostV2ServiceImpl.java
  main/src/test/java/org/sopt/makers/crew/main/comment/v2/service/CommentV2ServiceTest.java
  main/src/test/java/org/sopt/makers/crew/main/post/v2/service/PostV2ServiceTest.java
  server/src/post/v1/post-v1.controller.ts
Labels: 🎁 feature, size/L

#338 chore: 하나의 광고 이미지가 하나의 링크에 매핑되도록 수정
  main/src/main/java/org/sopt/makers/crew/main/advertisement/AdvertisementApi.java
  main/src/main/java/org/sopt/makers/crew/main/advertisement/AdvertisementController.java
  main/src/main/java/org/sopt/makers/crew/main/advertisement/dto/AdvertisementGetDto.java
  main/src/main/java/org/sopt/makers/crew/main/advertisement/dto/AdvertisementGetResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/advertisement/dto/AdvertisementImageDto.java
  main/src/main/java/org/sopt/makers/crew/main/advertisement/dto/AdvertisementsGetResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/advertisement/service/AdvertisementService.java
  main/src/main/java/org/sopt/makers/crew/main/entity/advertisement/Advertisement.java
  main/src/main/java/org/sopt/makers/crew/main/entity/advertisement/AdvertisementImage.java
  main/src/main/java/org/sopt/makers/crew/main/entity/advertisement/AdvertisementImageRepository.java
  main/src/main/java/org/sopt/makers/crew/main/entity/advertisement/AdvertisementRepository.java
Labels: size/L, 🪛 chore

#340 chore: 변수명 수정
  main/src/main/java/org/sopt/makers/crew/main/advertisement/dto/AdvertisementGetDto.java
  main/src/main/java/org/sopt/makers/crew/main/advertisement/dto/AdvertisementsGetResponseDto.java
Labels: size/S, 🪛 chore

#342 add: 코드 포맷터 추가
  main/style-config/naver-checkstyle-rules.xml
  main/style-config/naver-intellij-formatter.xml
Labels: 🏭 environment, size/L

#347 refactor: 모임 배너 조회 로직 개선
  main/src/main/java/org/sopt/makers/crew/main/entity/apply/Applies.java
  main/src/main/java/org/sopt/makers/crew/main/entity/apply/Apply.java
  main/src/main/java/org/sopt/makers/crew/main/entity/meeting/MeetingRepository.java
  main/src/main/java/org/sopt/makers/crew/main/entity/post/Post.java
  main/src/main/java/org/sopt/makers/crew/main/entity/post/PostRepository.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/response/MeetingV2GetMeetingBannerResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/response/MeetingV2GetMeetingBannerResponseUserDto.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2Service.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceImpl.java
Labels: size/XL

#352 fix: 이미지 nullable 하게 수정
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/request/MeetingV2ApplyMeetingDto.java
  main/src/main/java/org/sopt/makers/crew/main/post/v2/dto/request/PostV2CreatePostBodyDto.java
  main/src/main/java/org/sopt/makers/crew/main/post/v2/dto/request/PostV2UpdatePostBodyDto.java
Labels: 🐞 fix, size/S

#354 v2.0.1
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/request/MeetingV2ApplyMeetingDto.java
  main/src/main/java/org/sopt/makers/crew/main/post/v2/dto/request/PostV2CreatePostBodyDto.java
  main/src/main/java/org/sopt/makers/crew/main/post/v2/dto/request/PostV2UpdatePostBodyDto.java
Labels: size/S, 🚀 deployment, 3️⃣ patch
