Repository sopt-makers/sopt-crew-backend, pull requests merged in 2024-07, with the labels that each got.

#242 [FEAT] 모임 게시물 & 댓글에서 멘션 V2 API 구현
  main/src/main/java/org/sopt/makers/crew/main/comment/v2/CommentV2Api.java
  main/src/main/java/org/sopt/makers/crew/main/comment/v2/CommentV2Controller.java
  main/src/main/java/org/sopt/makers/crew/main/comment/v2/dto/request/CommentV2MentionUserInCommentRequestDto.java
  main/src/main/java/org/sopt/makers/crew/main/comment/v2/service/CommentV2Service.java
  main/src/main/java/org/sopt/makers/crew/main/comment/v2/service/CommentV2ServiceImpl.java
  main/src/main/java/org/sopt/makers/crew/main/entity/user/UserRepository.java
  main/src/main/java/org/sopt/makers/crew/main/internal/notification/PushNotificationEnums.java
  main/src/main/java/org/sopt/makers/crew/main/post/v2/PostV2Api.java
  main/src/main/java/org/sopt/makers/crew/main/post/v2/PostV2Controller.java
  main/src/main/java/org/sopt/makers/crew/main/post/v2/dto/request/PostV2MentionUserInPostRequestDto.java
  main/src/main/java/org/sopt/makers/crew/main/post/v2/service/PostV2Service.java
  main/src/main/java/org/sopt/makers/crew/main/post/v2/service/PostV2ServiceImpl.java
Labels: feature, size/XL

#243 [feature/#214] 댓글 수정 V2 API 구현
  docker-compose.yml
  main/src/main/java/org/sopt/makers/crew/main/comment/v2/CommentV2Api.java
  main/src/main/java/org/sopt/makers/crew/main/comment/v2/CommentV2Controller.java
  main/src/main/java/org/sopt/makers/crew/main/comment/v2/dto/request/CommentV2MentionUserInCommentRequestDto.java
  main/src/main/java/org/sopt/makers/crew/main/comment/v2/dto/request/CommentV2UpdateCommentBodyDto.java
  main/src/main/java/org/sopt/makers/crew/main/comment/v2/dto/response/CommentV2UpdateCommentResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/comment/v2/service/CommentV2Service.java
  main/src/main/java/org/sopt/makers/crew/main/comment/v2/service/CommentV2ServiceImpl.java
  main/src/main/java/org/sopt/makers/crew/main/common/util/RealTime.java
  main/src/main/java/org/sopt/makers/crew/main/common/util/Time.java
  main/src/main/java/org/sopt/makers/crew/main/entity/comment/Comment.java
  main/src/main/java/org/sopt/makers/crew/main/entity/user/UserRepository.java
  main/src/main/java/org/sopt/makers/crew/main/internal/notification/PushNotificationEnums.java
  main/src/main/java/org/sopt/makers/crew/main/post/v2/PostV2Api.java
  main/src/main/java/org/sopt/makers/crew/main/post/v2/PostV2Controller.java
  main/src/main/java/org/sopt/makers/crew/main/post/v2/dto/request/PostV2MentionUserInPostRequestDto.java
  main/src/main/java/org/sopt/makers/crew/main/post/v2/service/PostV2Service.java
  main/src/main/java/org/sopt/makers/crew/main/post/v2/service/PostV2ServiceImpl.java
  main/src/test/java/org/sopt/makers/crew/main/comment/v2/service/CommentV2ServiceTest.java
  main/src/test/java/org/sopt/makers/crew/main/common/util/StubTime.java
  server/src/comment/v1/comment-v1.controller.ts
Labels: size/XXL

#246 [FIX] 라우팅 규칙 편집
  docker-compose.yml
Labels: bug, size/S

#251 [FIX] userId -> orgId로 수정 및 orgId 필요한 로직에 데이터 추가
  main/src/main/java/org/sopt/makers/crew/main/comment/v2/dto/request/CommentV2MentionUserInCommentRequestDto.java
  main/src/main/java/org/sopt/makers/crew/main/comment/v2/dto/response/CommentDto.java
  main/src/main/java/org/sopt/makers/crew/main/comment/v2/dto/response/CommentWriterDto.java
  main/src/main/java/org/sopt/makers/crew/main/comment/v2/service/CommentV2ServiceImpl.java
  main/src/main/java/org/sopt/makers/crew/main/user/v2/dto/response/UserV2GetAllMentionUserDto.java
  main/src/main/java/org/sopt/makers/crew/main/user/v2/service/UserV2ServiceImpl.java
Labels: bug, size/M

#252 [FIX] 댓글 작성 알림 시 비밀문자열 제거
  main/src/main/java/org/sopt/makers/crew/main/comment/v2/service/CommentV2ServiceImpl.java
  main/src/main/java/org/sopt/makers/crew/main/common/util/MentionSecretStringRemover.java
Labels: size/XS

#255 [HOTFIX] 비밀문자열 패턴 수정
  main/src/main/java/org/sopt/makers/crew/main/common/util/MentionSecretStringRemover.java
Labels: bug, size/XS

#257 [CHORE] 알림 메세지 변경
  main/src/main/java/org/sopt/makers/crew/main/comment/v2/service/CommentV2ServiceImpl.java
  main/src/main/java/org/sopt/makers/crew/main/internal/notification/PushNotificationEnums.java
Labels: size/S, chore

#262 [FIX] 피드 작성 API 수정
  main/src/main/java/org/sopt/makers/crew/main/post/v2/service/PostV2ServiceImpl.java
Labels: bug, size/XS

#260 [CHORE] 댓글 삭제 기능 수정 및 댓글 수정 로직 일부 수정
  main/src/main/java/org/sopt/makers/crew/main/comment/v2/service/CommentV2Service.java
  main/src/main/java/org/sopt/makers/crew/main/comment/v2/service/CommentV2ServiceImpl.java
  main/src/main/java/org/sopt/makers/crew/main/common/util/MentionSecretStringRemover.java
  main/src/main/java/org/sopt/makers/crew/main/entity/comment/Comment.java
  main/src/main/java/org/sopt/makers/crew/main/entity/comment/CommentRepository.java
  main/src/main/java/org/sopt/makers/crew/main/entity/comment/Comments.java
Labels: size/XL, chore

#267 [FIX] 멘션 알림 멘트 변경
  main/src/main/java/org/sopt/makers/crew/main/comment/v2/service/CommentV2ServiceImpl.java
  main/src/main/java/org/sopt/makers/crew/main/internal/notification/PushNotificationEnums.java
Labels: bug, size/XS

#269 [CHORE] 큰 따옴표 추가
  main/src/main/java/org/sopt/makers/crew/main/comment/v2/service/CommentV2ServiceImpl.java
Labels: size/XS, chore

#274 v1.3.1
  main/src/main/java/org/sopt/makers/crew/main/post/v2/service/PostV2ServiceImpl.java
Labels: size/XS, deployment

#275 [FEAT] 모임 게시글 단일 조회 및 모임 게시글 개수 조회 V2 API 구현
  main/src/main/java/org/sopt/makers/crew/main/entity/like/LikeRepository.java
  main/src/main/java/org/sopt/makers/crew/main/entity/post/PostRepository.java
  main/src/main/java/org/sopt/makers/crew/main/entity/post/PostSearchRepository.java
  main/src/main/java/org/sopt/makers/crew/main/entity/post/PostSearchRepositoryImpl.java
  main/src/main/java/org/sopt/makers/crew/main/post/v2/PostV2Api.java
  main/src/main/java/org/sopt/makers/crew/main/post/v2/PostV2Controller.java
  main/src/main/java/org/sopt/makers/crew/main/post/v2/dto/response/PostMeetingDto.java
  main/src/main/java/org/sopt/makers/crew/main/post/v2/dto/response/PostV2GetPostCountResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/post/v2/service/PostV2Service.java
  main/src/main/java/org/sopt/makers/crew/main/post/v2/service/PostV2ServiceImpl.java
  main/src/test/java/org/sopt/makers/crew/main/post/v2/repository/PostRepositoryTest.java
  server/src/post/v1/post-v1.controller.ts
Labels: feature, size/L
