Repository sopt-makers/sopt-crew-backend, pull requests merged in 2024-06, with the labels that each got.

#208 [FIX] 메이커스 팀장 버그 & 라우팅 규칙 수정
  docker-compose.yml
  main/src/main/java/org/sopt/makers/crew/main/entity/user/enums/UserPart.java
  server/src/entity/user/enum/user-part.enum.ts
Labels: bug, size/S

#210 [FIX] 오류 수정
  docker-compose.yml
Labels: bug, size/XS

#223 [FEAT] 공지사항 관련 API 마이그레이션
  docker-compose.yml
  main/src/main/java/org/sopt/makers/crew/main/entity/notice/Notice.java
  main/src/main/java/org/sopt/makers/crew/main/entity/notice/NoticeRepository.java
  main/src/main/java/org/sopt/makers/crew/main/notice/NoticeV2Api.java
  main/src/main/java/org/sopt/makers/crew/main/notice/NoticeV2Controller.java
  main/src/main/java/org/sopt/makers/crew/main/notice/dto/request/NoticeV2CreateRequestDto.java
  main/src/main/java/org/sopt/makers/crew/main/notice/dto/response/NoticeV2GetResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/notice/service/NoticeV2Service.java
  main/src/main/resources/application-dev.yml
  main/src/main/resources/application-prod.yml
  main/src/main/resources/application-test.yml
Labels: feature, size/L

#228 [FIX] 라우팅 규칙 편집
  docker-compose.yml
Labels: bug, size/XS

#211 [FEAT] 모임 게시글 목록 조회 V2 API 구현
  docker-compose.yml
  main/src/main/java/org/sopt/makers/crew/main/common/config/JpaAuditingConfig.java
  main/src/main/java/org/sopt/makers/crew/main/entity/comment/Comment.java
  main/src/main/java/org/sopt/makers/crew/main/entity/like/Like.java
  main/src/main/java/org/sopt/makers/crew/main/entity/like/LikeRepository.java
  main/src/main/java/org/sopt/makers/crew/main/entity/post/Post.java
  main/src/main/java/org/sopt/makers/crew/main/entity/post/PostRepository.java
  main/src/main/java/org/sopt/makers/crew/main/entity/post/PostSearchRepository.java
  main/src/main/java/org/sopt/makers/crew/main/entity/post/PostSearchRepositoryImpl.java
  main/src/main/java/org/sopt/makers/crew/main/entity/user/User.java
  main/src/main/java/org/sopt/makers/crew/main/post/v2/PostV2Api.java
  main/src/main/java/org/sopt/makers/crew/main/post/v2/PostV2Controller.java
  main/src/main/java/org/sopt/makers/crew/main/post/v2/dto/query/PostGetPostsCommand.java
  main/src/main/java/org/sopt/makers/crew/main/post/v2/dto/response/CommenterThumbnails.java
  main/src/main/java/org/sopt/makers/crew/main/post/v2/dto/response/PostDetailBaseDto.java
  main/src/main/java/org/sopt/makers/crew/main/post/v2/dto/response/PostDetailResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/post/v2/dto/response/PostMeetingDto.java
  main/src/main/java/org/sopt/makers/crew/main/post/v2/dto/response/PostV2GetPostsResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/post/v2/dto/response/PostWriterInfoDto.java
  main/src/main/java/org/sopt/makers/crew/main/post/v2/service/PostV2Service.java
  main/src/main/java/org/sopt/makers/crew/main/post/v2/service/PostV2ServiceImpl.java
  main/src/test/java/org/sopt/makers/crew/main/common/config/TestConfig.java
  main/src/test/java/org/sopt/makers/crew/main/post/v2/repository/PostRepositoryTest.java
  main/src/test/resources/sql/post-repository-test-data.sql
  server/src/post/v1/post-v1.controller.ts
Labels: feature, size/XXL

#232 [FIX] Open API Spec에 맞춰서 게시글 목록 조회 API 파라미터 구조 수정
  main/src/main/java/org/sopt/makers/crew/main/post/v2/PostV2Api.java
  main/src/main/java/org/sopt/makers/crew/main/post/v2/PostV2Controller.java
  main/src/main/java/org/sopt/makers/crew/main/post/v2/dto/query/PostGetPostsCommand.java
Labels: size/S

#234 [FIX] Open API Spec에 맞춰서 쿼리 파라미터 타입 지정
  main/src/main/java/org/sopt/makers/crew/main/post/v2/PostV2Api.java
Labels: size/XS

#236 [CHORE] 공지사항 조회 API id 데이터 추가
  main/src/main/java/org/sopt/makers/crew/main/notice/dto/response/NoticeV2GetResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/notice/service/NoticeV2Service.java
Labels: size/XS, chore
