Repository sopt-makers/sopt-crew-backend, pull requests merged in 2024-03, with the labels that each got.

#133 [FIX] 플그 마이페이지 내 모임 조회 API, 401 에러 해결
  main/src/main/java/org/sopt/makers/crew/main/common/exception/NoContentException.java
  main/src/main/java/org/sopt/makers/crew/main/common/response/ErrorStatus.java
  main/src/main/java/org/sopt/makers/crew/main/entity/user/UserRepository.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceImpl.java
Labels: bug, size/M

#135 [CHORE] 활동기수 변경
  server/src/common/constant/active-generation.const.ts
Labels: size/XS

#137 [FIX] 플그 마이페이지 내 모임 조회 API, 204 status code 시 성공 response body로 내려가도록 수정
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/MeetingV2Controller.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceImpl.java
Labels: size/M

#144 [#143] 모임 게시글 작성 API 라우팅 규칙 변경
  docker-compose.yml
Labels: size/XS

#147 [FIX] 도커 컴포즈 TimeZone seoul 추가
  docker-compose.yml
Labels: bug, size/XS

#152 [CHORE] nest.js 의존성 추가
  package-lock.json
  server/package-lock.json
  server/package.json
Labels: size/XS
