Repository sopt-makers/sopt-crew-backend, pull requests merged in 2024-05, with the labels that each got.

#161 Feat/#145
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/cd-dev.yml
  .github/workflows/cd-prod.yml
  .github/workflows/ci.yml
  .github/workflows/dev-CD.yml
  .gitignore
  deploy-dev.sh
  deploy-prod.sh
  docker-compose.dev.yml
  docker-compose.local.yml
  docker-compose.prod.yml
  docker-compose.yml
  main/src/main/java/org/sopt/makers/crew/main/common/config/SecurityConfig.java
  main/src/main/java/org/sopt/makers/crew/main/health/v1/HealthController.java
Labels: size/XL

#176 [FIX] Route 규칙 변경
  docker-compose.yml
Labels: size/XS

#178 [CHORE] 로그에 sql 제거
  main/src/main/resources/application-prod.yml
Labels: size/XS, chore

#179 [FEAT] 모임 지원 신청/취소 API 마이그레이션
  main/src/main/java/org/sopt/makers/crew/main/common/response/ErrorStatus.java
  main/src/main/java/org/sopt/makers/crew/main/common/util/UserPartUtil.java
  main/src/main/java/org/sopt/makers/crew/main/entity/apply/Apply.java
  main/src/main/java/org/sopt/makers/crew/main/entity/apply/ApplyRepository.java
  main/src/main/java/org/sopt/makers/crew/main/entity/meeting/Meeting.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/MeetingV2Api.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/MeetingV2Controller.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/ApplyMapper.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/request/MeetingV2ApplyMeetingCancelBodyDto.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/request/MeetingV2ApplyMeetingDto.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/response/MeetingV2ApplyMeetingResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2Service.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceImpl.java
  main/src/main/java/org/sopt/makers/crew/main/post/v2/PostV2Controller.java
  main/src/test/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceTest.java
  server/src/meeting/v0/meeting-v0.controller.ts
  server/src/meeting/v1/meeting-v1.controller.ts
  server/src/post/v1/post-v1.controller.ts
Labels: size/XXL

#182 [FEAT] 모임 지원 취소 API 수정
  main/src/main/java/org/sopt/makers/crew/main/entity/apply/ApplyRepository.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/MeetingV2Api.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/MeetingV2Controller.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2Service.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceImpl.java
Labels: size/M

#184 [CHORE] 모임 지원/취소 API 에러 메세지 수정
  main/src/main/java/org/sopt/makers/crew/main/common/response/ErrorStatus.java
Labels: size/XS

#180 Hotfix/cicd workflow 수정
  .github/workflows/cd-dev.yml
  .github/workflows/cd-prod.yml
  .github/workflows/ci.yml
Labels: size/S

#189 Fix/#188
  server/src/auth/v0/auth-v0.service.ts
  server/src/entity/user/enum/user-part.enum.ts
  server/src/internal-api/playground/dto/get-user-activities/playground-repository-get-user-activity-info.dto.ts
  server/src/internal-api/playground/dto/get-user-activities/playground-repository-get-user-activity.dto.ts
  server/src/internal-api/playground/dto/get-user-profile/playground-repository-get-user-profile-activity-cardinal-activity.dto.ts
  server/src/internal-api/playground/playground.repository.ts
  server/src/internal-api/playground/playground.service.ts
Labels: bug, size/L

#187 [CHORE] logger 개선
  docker-compose.yml
  server/src/app.module.ts
  server/src/common/middleware/logger.middleware.ts
  server/src/main.ts
Labels: size/M

#190 Hotfix/#190
  main/src/main/java/org/sopt/makers/crew/main/entity/user/enums/UserPart.java
  server/src/auth/v0/auth-v0.service.ts
  server/src/entity/user/enum/user-part.enum.ts
Labels: size/M

#195 [FIX] 스웨거 이슈 해결
  main/src/main/java/org/sopt/makers/crew/main/common/config/SecurityConfig.java
Labels: bug, size/XS

#197 v1.2.6
  main/src/main/java/org/sopt/makers/crew/main/common/config/SecurityConfig.java
Labels: size/XS, deployment

#200 [FIX] 피드 작성 시간 표기 오류
  server/src/post/v1/dto/get-meeting-post/post-v1-get-post-response.dto.ts
  server/src/post/v1/dto/get-meeting-posts/post-v1-get-posts-response-post.dto.ts
  server/src/post/v1/post-v1.service.ts
Labels: bug, size/S
