Repository sopt-makers/sopt-crew-backend, pull requests merged in 2025-02, with the labels that each got.

#567 chore: 변경된 DTO 네이밍 적용
  main/src/main/java/org/sopt/makers/crew/main/flash/v2/dto/request/FlashV2CreateAndUpdateFlashBodyDto.java
  main/src/main/java/org/sopt/makers/crew/main/flash/v2/dto/request/FlashV2CreateAndUpdateFlashBodyWithoutWelcomeMessageDto.java
  main/src/main/java/org/sopt/makers/crew/main/flash/v2/dto/response/FlashV2CreateAndUpdateResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/response/MeetingV2CreateAndUpdateMeetingForFlashResponseDto.java
Labels: size/XS, 🪛 chore

#571 chore(Meeting): 상황에 따라 광고 페이지네이션과 커스텀 페이지네이션 동적으로 구현
  main/src/main/java/org/sopt/makers/crew/main/global/pagination/AdvertisementPageableStrategy.java
  main/src/main/java/org/sopt/makers/crew/main/global/pagination/DefaultPageableStrategy.java
  main/src/main/java/org/sopt/makers/crew/main/global/pagination/PageableStrategy.java
  main/src/main/java/org/sopt/makers/crew/main/global/pagination/PaginationType.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/query/MeetingV2GetAllMeetingQueryDto.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceImpl.java
Labels: size/M, 🪛 chore

#572 fix(Meeting): paginationType 스웨거 추가
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/MeetingV2Api.java
Labels: 🐞 fix, size/XS

#573 refactor: 모집중, 모집전, 모집마감 순으로 모임조회 정렬 정책 변경
  main/.gitignore
  main/src/main/java/org/sopt/makers/crew/main/entity/meeting/MeetingSearchRepositoryImpl.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceImpl.java
  main/src/test/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceTest.java
Labels: 🛠️ refactor, size/L
