Repository sopt-makers/sopt-crew-backend, pull requests merged in 2025-05, with the labels that each got.

#654 feat: 모임 신청 부하 테스트를 위한 api 비즈니스 로직들 구현 진행
  .github/workflows/cd-traffic.yml
  main/src/main/java/org/sopt/makers/crew/main/entity/apply/enums/EnApplyType.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/MeetingV2Controller.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2Service.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceImpl.java
Labels: 🎁 feature, size/M

#651 feat: 모임 키워드 태그 및 환영 태그 기능 통합 개발 완료
  main/src/main/java/org/sopt/makers/crew/main/entity/meeting/MeetingSearchRepositoryImpl.java
  main/src/main/java/org/sopt/makers/crew/main/entity/tag/Tag.java
  main/src/main/java/org/sopt/makers/crew/main/entity/tag/TagRepository.java
  main/src/main/java/org/sopt/makers/crew/main/entity/tag/projection/MeetingKeywordsTypeProjection.java
  main/src/main/java/org/sopt/makers/crew/main/entity/tag/projection/MeetingTagInfoProjection.java
  main/src/main/java/org/sopt/makers/crew/main/entity/tag/projection/WelcomeMessageTypeProjection.java
  main/src/main/java/org/sopt/makers/crew/main/flash/v2/FlashV2Api.java
  main/src/main/java/org/sopt/makers/crew/main/flash/v2/FlashV2Controller.java
  main/src/main/java/org/sopt/makers/crew/main/flash/v2/dto/request/FlashV2CreateAndUpdateFlashBodyDto.java
  main/src/main/java/org/sopt/makers/crew/main/flash/v2/dto/response/FlashV2CreateResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/flash/v2/dto/response/FlashV2GetFlashByMeetingIdResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/flash/v2/service/FlashV2Service.java
  main/src/main/java/org/sopt/makers/crew/main/flash/v2/service/FlashV2ServiceImpl.java
  main/src/main/java/org/sopt/makers/crew/main/global/dto/MeetingResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/MeetingV2Api.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/MeetingV2Controller.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/MeetingMapper.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/query/MeetingV2GetAllMeetingQueryDto.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/redis/MeetingCacheDto.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/request/MeetingV2CreateAndUpdateMeetingBodyDto.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/response/MeetingV2CreateMeetingResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/response/MeetingV2GetMeetingByIdResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2Service.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceImpl.java
  main/src/main/java/org/sopt/makers/crew/main/tag/v2/dto/response/TagV2CreateAndUpdateFlashTagResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/tag/v2/dto/response/TagV2CreateFlashTagResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/tag/v2/dto/response/TagV2CreateGeneralMeetingTagResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/tag/v2/dto/response/TagV2MeetingTagsResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/tag/v2/service/TagV2Service.java
  main/src/main/java/org/sopt/makers/crew/main/tag/v2/service/TagV2ServiceImpl.java
  main/src/main/resources/schema.sql
  main/src/test/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceTest.java
  main/src/test/resources/sql/delete-all-data.sql
  main/src/test/resources/sql/meeting-service-test-data.sql
Labels: 🎁 feature, size/XL

#645 feat: cache clear 작업 진행
  main/src/main/java/org/sopt/makers/crew/main/external/caffeine/CacheQueryService.java
  main/src/main/java/org/sopt/makers/crew/main/external/caffeine/CachesEndpointExtension.java
  main/src/main/resources/application-dev.yml
  main/src/main/resources/application-prod.yml
  main/src/main/resources/application-test.yml
  main/src/main/resources/application-traffic.yml
  main/src/test/java/org/sopt/makers/crew/main/external/CaffeineCacheTest.java
Labels: 🎁 feature, size/L

#655 Sp1 before backup -> traffic으로 머지 진행
  main/build.gradle
  main/src/main/java/org/sopt/makers/crew/main/auth/v2/service/AuthV2ServiceImpl.java
  main/src/main/java/org/sopt/makers/crew/main/entity/flash/Flash.java
  main/src/main/java/org/sopt/makers/crew/main/entity/meeting/MeetingReader.java
  main/src/main/java/org/sopt/makers/crew/main/entity/user/UserReader.java
  main/src/main/java/org/sopt/makers/crew/main/external/caffeine/CacheInfo.java
  main/src/main/java/org/sopt/makers/crew/main/external/caffeine/CacheQueryService.java
  main/src/main/java/org/sopt/makers/crew/main/external/caffeine/CachesEndpointExtension.java
  main/src/main/java/org/sopt/makers/crew/main/external/caffeine/CaffeineConfig.java
  main/src/main/java/org/sopt/makers/crew/main/external/redis/RedisConfig.java
  main/src/main/java/org/sopt/makers/crew/main/flash/v2/FlashV2Controller.java
  main/src/main/java/org/sopt/makers/crew/main/flash/v2/dto/event/FlashLeaderSyncEventDto.java
  main/src/main/java/org/sopt/makers/crew/main/flash/v2/event/FlashLeaderSyncEventListener.java
  main/src/main/java/org/sopt/makers/crew/main/flash/v2/service/FlashV2Service.java
  main/src/main/java/org/sopt/makers/crew/main/flash/v2/service/FlashV2ServiceImpl.java
  main/src/main/java/org/sopt/makers/crew/main/global/config/SecurityConfig.java
  main/src/main/java/org/sopt/makers/crew/main/global/dto/MeetingCreatorDto.java
  main/src/main/java/org/sopt/makers/crew/main/global/dto/MeetingResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/MeetingV2Controller.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/redis/MeetingCacheDto.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/response/MeetingLeaderUserIdDto.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2Service.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceImpl.java
  main/src/main/java/org/sopt/makers/crew/main/user/v2/dto/response/MeetingV2GetCreatedMeetingByUserResponseDto.java
  main/src/main/resources/application-dev.yml
  main/src/main/resources/application-prod.yml
  main/src/main/resources/application-test.yml
  main/src/main/resources/application-traffic.yml
  main/src/main/resources/logback-spring.xml
  main/src/test/java/org/sopt/makers/crew/main/external/CaffeineTestConfig.java
  main/src/test/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceTest.java
Labels: size/XL

#660 refactor: 필터링 교집합 조건 합집합 조건으로 변경 완료
  main/src/main/java/org/sopt/makers/crew/main/entity/meeting/MeetingSearchRepositoryImpl.java
Labels: 🛠️ refactor, size/S

#658 feat: editable 컨텐츠를 위한 admin api 를 만들어요 (1차 배포)
  main/build.gradle
  main/src/main/java/org/sopt/makers/crew/main/admin/v2/AdminV2Controller.java
  main/src/main/java/org/sopt/makers/crew/main/admin/v2/PropertyV2Api.java
  main/src/main/java/org/sopt/makers/crew/main/admin/v2/PropertyV2Controller.java
  main/src/main/java/org/sopt/makers/crew/main/admin/v2/dto/HomePropertyResponse.java
  main/src/main/java/org/sopt/makers/crew/main/admin/v2/dto/PropertyResponse.java
  main/src/main/java/org/sopt/makers/crew/main/admin/v2/service/AdminFacade.java
  main/src/main/java/org/sopt/makers/crew/main/admin/v2/service/AdminKeyProvider.java
  main/src/main/java/org/sopt/makers/crew/main/admin/v2/service/AdminService.java
  main/src/main/java/org/sopt/makers/crew/main/admin/v2/service/AdminServiceImpl.java
  main/src/main/java/org/sopt/makers/crew/main/admin/v2/service/JsonPrettierService.java
  main/src/main/java/org/sopt/makers/crew/main/admin/v2/service/JsonPrettierServiceImpl.java
  main/src/main/java/org/sopt/makers/crew/main/admin/v2/service/dto/AdminPagePresenter.java
  main/src/main/java/org/sopt/makers/crew/main/admin/v2/service/dto/HomeProperties.java
  main/src/main/java/org/sopt/makers/crew/main/admin/v2/service/vo/MainPageContentVo.java
  main/src/main/java/org/sopt/makers/crew/main/admin/v2/service/vo/PropertyVo.java
  main/src/main/java/org/sopt/makers/crew/main/entity/property/Property.java
  main/src/main/java/org/sopt/makers/crew/main/entity/property/PropertyRepository.java
  main/src/main/java/org/sopt/makers/crew/main/global/config/SecurityConfig.java
  main/src/main/resources/application-dev.yml
  main/src/main/resources/application-prod.yml
  main/src/main/resources/application-test.yml
  main/src/main/resources/application-traffic.yml
  main/src/main/resources/templates/propertyPage.html
Labels: size/XL

#662 refactor: 기획 정책 변경으로 인한 모임 키워드 로직 리팩토링 완료
  main/src/main/java/org/sopt/makers/crew/main/entity/tag/enums/MeetingKeywordType.java
  main/src/main/java/org/sopt/makers/crew/main/flash/v2/dto/request/FlashV2CreateAndUpdateFlashBodyDto.java
  main/src/main/java/org/sopt/makers/crew/main/global/dto/MeetingResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/MeetingV2Api.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/request/MeetingV2CreateAndUpdateMeetingBodyDto.java
  main/src/main/java/org/sopt/makers/crew/main/user/v2/dto/response/MeetingV2GetCreatedMeetingByUserResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/user/v2/dto/response/UserV2GetAppliedMeetingByUserResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/user/v2/dto/response/UserV2GetCreatedMeetingByUserResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/user/v2/service/UserV2ServiceImpl.java
  main/src/test/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceTest.java
  main/src/test/java/org/sopt/makers/crew/main/user/v2/UserServiceTest.java
  main/src/test/resources/sql/user-service-test-data.sql
Labels: 🛠️ refactor, size/L

#663 refactor: fe의 요청에 따라 응답 형태를 변경하였어요!
  main/src/main/java/org/sopt/makers/crew/main/admin/v2/PropertyV2Controller.java
  main/src/main/java/org/sopt/makers/crew/main/admin/v2/dto/PropertyResponse.java
  main/src/main/java/org/sopt/makers/crew/main/admin/v2/dto/PropertyValueResponse.java
  main/src/main/java/org/sopt/makers/crew/main/admin/v2/service/AdminFacade.java
  main/src/main/java/org/sopt/makers/crew/main/admin/v2/service/AdminServiceImpl.java
  main/src/main/java/org/sopt/makers/crew/main/admin/v2/service/JsonPrettierServiceImpl.java
  main/src/main/java/org/sopt/makers/crew/main/admin/v2/service/dto/PropertyDto.java
  main/src/main/java/org/sopt/makers/crew/main/admin/v2/service/vo/MainPageContentVo.java
  main/src/main/java/org/sopt/makers/crew/main/global/exception/ErrorStatus.java
Labels: 🛠️ refactor, size/M

#664 refactor: api 응답 방식 변경
  main/src/main/java/org/sopt/makers/crew/main/admin/v2/AdminV2Controller.java
  main/src/main/java/org/sopt/makers/crew/main/admin/v2/PropertyV2Api.java
  main/src/main/java/org/sopt/makers/crew/main/admin/v2/PropertyV2Controller.java
  main/src/main/java/org/sopt/makers/crew/main/admin/v2/dto/AdminPagePresenter.java
  main/src/main/java/org/sopt/makers/crew/main/admin/v2/dto/HomeProperties.java
  main/src/main/java/org/sopt/makers/crew/main/admin/v2/dto/PropertyDto.java
  main/src/main/java/org/sopt/makers/crew/main/admin/v2/dto/PropertyResponse.java
  main/src/main/java/org/sopt/makers/crew/main/admin/v2/service/AdminFacade.java
  main/src/main/java/org/sopt/makers/crew/main/admin/v2/service/AdminService.java
  main/src/main/java/org/sopt/makers/crew/main/admin/v2/service/AdminServiceImpl.java
  main/src/main/java/org/sopt/makers/crew/main/admin/v2/service/strategy/AllPropertiesStrategy.java
  main/src/main/java/org/sopt/makers/crew/main/admin/v2/service/strategy/PropertyResponseStrategy.java
  main/src/main/java/org/sopt/makers/crew/main/admin/v2/service/strategy/PropertyStrategyManager.java
  main/src/main/java/org/sopt/makers/crew/main/admin/v2/service/strategy/SinglePropertiesStrategy.java
  main/src/main/java/org/sopt/makers/crew/main/global/exception/ErrorStatus.java
Labels: 🛠️ refactor, size/L

#667 fix: 모임 동시 신청 시 중복 신청 발생 문제 해결
  main/src/main/java/org/sopt/makers/crew/main/entity/meeting/Meeting.java
  main/src/main/java/org/sopt/makers/crew/main/global/exception/ErrorStatus.java
  main/src/main/java/org/sopt/makers/crew/main/global/exception/LockedException.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/MeetingV2Controller.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2Service.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceImpl.java
  main/src/main/java/org/sopt/makers/crew/main/user/v2/service/lock/UserLockManager.java
  main/src/test/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ConcurrencyTest.java
  main/src/test/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceTest.java
Labels: 🐞 fix, size/XL

#676 feat: 오후 10시 이후 오전 8시 이전엔 번쩍 생성 알림이 가지 않도록 진행해요!
  main/src/main/java/org/sopt/makers/crew/main/external/notification/event/NotificationTimeValidator.java
  main/src/main/java/org/sopt/makers/crew/main/flash/v2/service/FlashV2ServiceImpl.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceImpl.java
  main/src/test/java/org/sopt/makers/crew/main/external/notification/event/NotificationTimeValidatorTest.java
Labels: size/M

#677 V2.8.0
  main/src/main/java/org/sopt/makers/crew/main/entity/meeting/Meeting.java
  main/src/main/java/org/sopt/makers/crew/main/entity/meeting/enums/MeetingCategory.java
  main/src/main/java/org/sopt/makers/crew/main/entity/user/User.java
  main/src/main/java/org/sopt/makers/crew/main/entity/user/UserReader.java
  main/src/main/java/org/sopt/makers/crew/main/external/notification/PushNotificationEnums.java
  main/src/main/java/org/sopt/makers/crew/main/external/notification/dto/event/KeywordEventDto.java
  main/src/main/java/org/sopt/makers/crew/main/external/notification/event/KeywordMatchedUserNotificationEventListener.java
  main/src/main/java/org/sopt/makers/crew/main/external/notification/event/NotificationTimeValidator.java
  main/src/main/java/org/sopt/makers/crew/main/external/notification/vo/KeywordMatchedUserDto.java
  main/src/main/java/org/sopt/makers/crew/main/flash/v2/service/FlashV2ServiceImpl.java
  main/src/main/java/org/sopt/makers/crew/main/global/exception/ErrorStatus.java
  main/src/main/java/org/sopt/makers/crew/main/global/exception/LockedException.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/MeetingV2Controller.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2Service.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceImpl.java
  main/src/main/java/org/sopt/makers/crew/main/user/v2/UserV2Api.java
  main/src/main/java/org/sopt/makers/crew/main/user/v2/UserV2Controller.java
  main/src/main/java/org/sopt/makers/crew/main/user/v2/dto/UpdateUserInterestKeywordRequestDto.java
  main/src/main/java/org/sopt/makers/crew/main/user/v2/service/UserV2Service.java
  main/src/main/java/org/sopt/makers/crew/main/user/v2/service/UserV2ServiceImpl.java
  main/src/main/java/org/sopt/makers/crew/main/user/v2/service/lock/UserLockManager.java
  main/src/main/resources/schema.sql
  main/src/test/java/org/sopt/makers/crew/main/external/notification/event/NotificationTimeValidatorTest.java
  main/src/test/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ConcurrencyTest.java
  main/src/test/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceTest.java
Labels: size/XL, 🚀 deployment
