Repository sopt-makers/sopt-crew-backend, pull requests merged in 2025-09, with the labels that each got.

#731 fix: CI/CD 스크립트에서 Dockerfile 경로 수정
  .github/workflows/dev-ci-cd.yml
  .github/workflows/prod-ci-cd.yml
  .github/workflows/traffic-ci-cd.yml
Labels: size/S

#733 v2.9.4
  .github/workflows/cd-dev.yml
  .github/workflows/cd-prod.yml
  .github/workflows/cd-traffic.yml
  .github/workflows/ci-pr.yml
  .github/workflows/ci.yml
  .github/workflows/dev-ci-cd.yml
  .github/workflows/prod-ci-cd.yml
  .github/workflows/traffic-ci-cd.yml
Labels: size/L, 🚀 deployment, 3️⃣ patch

#734 chore: prod 배포 스크립트에 사용하지 않는 VERSION_TAG 환경변수 제거
  .github/workflows/prod-ci-cd.yml
Labels: size/XS, 🪛 chore

#736 feat: 최신기수를 관리하는 ACTIVE_GENERATION 상수값을 36에서 37로 변경
  .github/workflows/prod-ci-cd.yml
  main/src/main/java/org/sopt/makers/crew/main/global/constant/CrewConst.java
Labels: size/XS

#737 v2.9.6
  .github/workflows/prod-ci-cd.yml
  main/src/main/java/org/sopt/makers/crew/main/global/constant/CrewConst.java
Labels: size/XS, 🚀 deployment, 3️⃣ patch

#741 v2.9.7
  main/src/main/java/org/sopt/makers/crew/main/internal/dto/InternalPostResponseDto.java
Labels: size/XS
