Repository sopt-makers/sopt-crew-backend, pull requests merged in 2025-08, with the labels that each got.

#703 feat: meetingId 추가하여 dto 설정 진행
  main/src/main/java/org/sopt/makers/crew/main/internal/dto/InternalPostResponseDto.java
Labels: size/S

#700 feat: repository 코드 crew, platform 분리하여 진행할 수 있도록 수정
  main/src/main/java/org/sopt/makers/crew/main/entity/like/LikeRepository.java
  main/src/main/java/org/sopt/makers/crew/main/entity/meeting/MeetingRepository.java
  main/src/main/java/org/sopt/makers/crew/main/entity/meeting/MeetingSearchRepository.java
  main/src/main/java/org/sopt/makers/crew/main/entity/meeting/MeetingSearchRepositoryImpl.java
  main/src/main/java/org/sopt/makers/crew/main/entity/post/PostSearchRepository.java
  main/src/main/java/org/sopt/makers/crew/main/entity/post/PostSearchRepositoryImpl.java
  main/src/main/java/org/sopt/makers/crew/main/entity/user/CrewRepository.java
  main/src/main/java/org/sopt/makers/crew/main/entity/user/PlatformUserRepository.java
  main/src/main/java/org/sopt/makers/crew/main/entity/user/PlatformUserRepositoryImpl.java
  main/src/main/java/org/sopt/makers/crew/main/entity/user/User.java
  main/src/main/java/org/sopt/makers/crew/main/entity/user/UserReader.java
  main/src/main/java/org/sopt/makers/crew/main/entity/user/UserRepository.java
  main/src/main/java/org/sopt/makers/crew/main/entity/user/UserRepositoryImpl.java
  main/src/main/java/org/sopt/makers/crew/main/entity/user/projection/UserKeywordsProjection.java
  main/src/main/java/org/sopt/makers/crew/main/external/auth/AuthClient.java
  main/src/main/java/org/sopt/makers/crew/main/external/auth/AuthService.java
  main/src/main/java/org/sopt/makers/crew/main/external/auth/dto/request/AuthUserRequestDto.java
  main/src/main/java/org/sopt/makers/crew/main/external/auth/dto/response/AuthApiResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/external/notification/dto/event/FlashCreatedEventDto.java
  main/src/main/java/org/sopt/makers/crew/main/external/notification/event/FlashCreatedEventListener.java
  main/src/main/java/org/sopt/makers/crew/main/flash/v2/service/FlashV2ServiceImpl.java
  main/src/main/java/org/sopt/makers/crew/main/internal/InternalMeetingApi.java
  main/src/main/java/org/sopt/makers/crew/main/internal/InternalMeetingController.java
  main/src/main/java/org/sopt/makers/crew/main/internal/InternalMeetingStatsApi.java
  main/src/main/java/org/sopt/makers/crew/main/internal/InternalMeetingStatsController.java
  main/src/main/java/org/sopt/makers/crew/main/internal/InternalPostApi.java
  main/src/main/java/org/sopt/makers/crew/main/internal/InternalPostController.java
  main/src/main/java/org/sopt/makers/crew/main/internal/dto/InternalMeetingForWritingPostDto.java
  main/src/main/java/org/sopt/makers/crew/main/internal/dto/InternalMeetingGetAllWritingPostResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/internal/dto/InternalPostGetAllResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/internal/dto/InternalPostLikeRequestDto.java
  main/src/main/java/org/sopt/makers/crew/main/internal/dto/InternalPostLikeResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/internal/dto/InternalPostResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/internal/dto/InternalPostWriterDetailInfoDto.java
  main/src/main/java/org/sopt/makers/crew/main/internal/service/InternalMeetingService.java
  main/src/main/java/org/sopt/makers/crew/main/internal/service/InternalMeetingStatsService.java
  main/src/main/java/org/sopt/makers/crew/main/internal/service/InternalPostService.java
  main/src/main/java/org/sopt/makers/crew/main/post/v2/dto/response/PostDetailWithPartBaseDto.java
  main/src/main/java/org/sopt/makers/crew/main/post/v2/dto/response/PostWriterWithPartInfoDto.java
  main/src/main/java/org/sopt/makers/crew/main/user/v2/UserV2Api.java
  main/src/main/java/org/sopt/makers/crew/main/user/v2/UserV2Controller.java
  main/src/main/java/org/sopt/makers/crew/main/user/v2/dto/UpdateUserInterestKeywordRequestDto.java
  main/src/main/java/org/sopt/makers/crew/main/user/v2/dto/response/UserV2GetInterestedKeywordsResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/user/v2/service/UserV2Service.java
  main/src/main/java/org/sopt/makers/crew/main/user/v2/service/UserV2ServiceImpl.java
  main/src/test/java/org/sopt/makers/crew/main/user/v2/UserServiceTest.java
Labels: size/XXL

#705 fix: 인증 마이그레이션 작업 수정
  main/src/main/java/org/sopt/makers/crew/main/entity/user/PlatformUserRepositoryImpl.java
  main/src/main/java/org/sopt/makers/crew/main/global/config/SecurityConfig.java
  main/src/main/java/org/sopt/makers/crew/main/global/security/filter/JwtAuthenticationFilter.java
Labels: 🐞 fix, size/S

#707 fix: allowCredential True로 변경하여 preFlight 실패하지 않도록 수정
  main/src/main/java/org/sopt/makers/crew/main/global/config/WebMvcConfig.java
Labels: size/XS

#710 chore: 모임 조회 및 지원자 조회 API의 queryCommand 파라미터를 Swagger 문서에서 hidden 처리
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/MeetingV2Api.java
Labels: size/M, 🪛 chore

#717 v2.9.1
  main/src/main/resources/application-prod.yml
Labels: size/XS, 🚀 deployment, 3️⃣ patch

#720 refactor: 보안 관련 설정을 SecurityConfig 한 곳에서 통합 관리 및 allowCredentials를 false로 변경
  main/src/main/java/org/sopt/makers/crew/main/global/config/SecurityConfig.java
  main/src/main/java/org/sopt/makers/crew/main/global/config/WebMvcConfig.java
Labels: size/M

#721 fix: 테스트 진행 시 다른 테스트에서의 영향을 더 받지 않도록 sleep기간 늘리는 작업 진행
  main/src/test/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ConcurrencyTest.java
Labels: size/XS
