Repository sopt-makers/sopt-crew-backend, pull requests merged in 2025-04, with the labels that each got.

#621 fix: 트리거한 워크플로우의 브랜치를 자동으로 가져오도록 수정 완료
  .github/workflows/cd-traffic.yml
Labels: 🐞 fix, size/XS

#613 fix: thread name prefix 오타 수정
  .github/workflows/cd-traffic.yml
  main/scripts/entrypoint.sh
  main/src/main/java/org/sopt/makers/crew/main/global/config/CrewDatabaseConfig.java
  main/src/main/java/org/sopt/makers/crew/main/global/config/PlaygroundDataSourceConfig.java
  main/src/main/java/org/sopt/makers/crew/main/global/util/RealTime.java
  main/src/main/resources/application-traffic.yml
  main/src/main/resources/logback-spring.xml
Labels: 🐞 fix, size/M

#623 refactor: test.yml에 caffeine cache 설정 추가
  main/src/main/resources/application-test.yml
Labels: 🛠️ refactor, size/S

#624 fix: 모임 삭제 시 관련된 모든 캐시 항목을 제거하도록 수정
  main/src/main/java/org/sopt/makers/crew/main/entity/user/UserReader.java
  main/src/main/java/org/sopt/makers/crew/main/global/dto/MeetingCreatorDto.java
  main/src/main/java/org/sopt/makers/crew/main/global/dto/MeetingResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceImpl.java
  main/src/main/java/org/sopt/makers/crew/main/user/v2/dto/response/MeetingV2GetCreatedMeetingByUserResponseDto.java
Labels: 🐞 fix, size/M

#625 refactor: 번쩍 상세 조회 전, meeting과 flash 테이블의 userId 정합성 검증 및 동기화 로직 추가
  main/src/main/java/org/sopt/makers/crew/main/entity/flash/Flash.java
  main/src/main/java/org/sopt/makers/crew/main/flash/v2/FlashV2Controller.java
  main/src/main/java/org/sopt/makers/crew/main/flash/v2/service/FlashV2Service.java
  main/src/main/java/org/sopt/makers/crew/main/flash/v2/service/FlashV2ServiceImpl.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/MeetingV2Controller.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/response/MeetingLeaderUserIdDto.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2Service.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceImpl.java
  main/src/test/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceTest.java
Labels: 🛠️ refactor, size/L

#627 fix: Flash 리더 정보 동기화 로직을 이벤트 기반 비동기 처리 방식으로 개선
  main/src/main/java/org/sopt/makers/crew/main/flash/v2/dto/event/FlashLeaderSyncEventDto.java
  main/src/main/java/org/sopt/makers/crew/main/flash/v2/event/FlashLeaderSyncEventListener.java
  main/src/main/java/org/sopt/makers/crew/main/flash/v2/service/FlashV2ServiceImpl.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2Service.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceImpl.java
Labels: 🐞 fix, size/L

#629 chore: 로그인 API에 토큰 로깅 추가 완료
  main/src/main/java/org/sopt/makers/crew/main/auth/v2/service/AuthV2ServiceImpl.java
Labels: size/S, 🪛 chore

#633 fix: 공동모임장인 경우 내 모임에 뜨지 않는 사항 수정
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceImpl.java
Labels: 🐞 fix, size/S

#641 v2.6.3
  main/src/main/resources/application-dev.yml
  main/src/main/resources/application-prod.yml
  main/src/main/resources/application-test.yml
  main/src/main/resources/application-traffic.yml
Labels: size/M, 🚀 deployment, 3️⃣ patch

#643 feat: 번쩍 개설 및 수정 시 모임 키워드 등록 기능 구현 완료
  main/src/main/java/org/sopt/makers/crew/main/entity/tag/Tag.java
  main/src/main/java/org/sopt/makers/crew/main/entity/tag/enums/MeetingKeywordType.java
  main/src/main/java/org/sopt/makers/crew/main/entity/tag/enums/WelcomeMessageType.java
  main/src/main/java/org/sopt/makers/crew/main/flash/v2/FlashV2Api.java
  main/src/main/java/org/sopt/makers/crew/main/flash/v2/dto/request/FlashV2CreateAndUpdateFlashBodyDto.java
  main/src/main/java/org/sopt/makers/crew/main/flash/v2/dto/response/FlashV2CreateAndUpdateResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/flash/v2/service/FlashV2ServiceImpl.java
  main/src/main/java/org/sopt/makers/crew/main/global/exception/ErrorStatus.java
  main/src/main/java/org/sopt/makers/crew/main/tag/v2/dto/response/TagV2CreateAndUpdateFlashTagResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/tag/v2/dto/response/TagV2CreateFlashTagResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/tag/v2/service/TagV2Service.java
  main/src/main/java/org/sopt/makers/crew/main/tag/v2/service/TagV2ServiceImpl.java
Labels: 🎁 feature, size/L

#646 v2.6.4
  .github/release-drafter-config.yml
  main/src/main/java/org/sopt/makers/crew/main/entity/meeting/CoLeaderRepository.java
  main/src/main/java/org/sopt/makers/crew/main/post/v2/service/PostV2ServiceImpl.java
Labels: size/S, 🚀 deployment, 3️⃣ patch, 🔥 hotfix

#647 hotfix: 공동모임장도 모임 게시글을 작성할 수 있도록 수정
  .github/release-drafter-config.yml
  main/src/main/java/org/sopt/makers/crew/main/entity/meeting/CoLeaderRepository.java
  main/src/main/java/org/sopt/makers/crew/main/post/v2/service/PostV2ServiceImpl.java
Labels: size/S, 🔥 hotfix

#648 v2.6.5
  .github/workflows/cd-prod.yml
Labels: size/XS, 🚀 deployment, 3️⃣ patch, 🔥 hotfix

#638 chore: 토큰 검증 예외 로그 레벨 error에서 warn으로 변경
  main/src/main/java/org/sopt/makers/crew/main/global/jwt/JwtTokenProvider.java
  main/src/main/resources/application-dev.yml
  main/src/main/resources/application-prod.yml
  main/src/main/resources/application-test.yml
  main/src/main/resources/application-traffic.yml
Labels: size/M, 🪛 chore
