Repository sopt-makers/sopt-crew-backend, pull requests merged in 2025-01, with the labels that each got.

#519 refactor: LazyConnectionDataSourceProxy 적용
  main/src/main/java/org/sopt/makers/crew/main/global/config/CrewDatabaseConfig.java
  main/src/main/resources/application-local.yml
Labels: 🛠️ refactor, size/M

#523 feat: 추천 모임 목록 조회 구현
  main/src/main/java/org/sopt/makers/crew/main/entity/meeting/MeetingSearchRepository.java
  main/src/main/java/org/sopt/makers/crew/main/entity/meeting/MeetingSearchRepositoryImpl.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/MeetingV2Api.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/MeetingV2Controller.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/response/MeetingV2GetRecommendDto.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2Service.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceImpl.java
Labels: 🎁 feature, size/M

#508 feat: 번쩍 관련 객체 정의
  main/src/main/java/org/sopt/makers/crew/main/entity/lightning/Lightning.java
  main/src/main/java/org/sopt/makers/crew/main/entity/lightning/LightningPlaceType.java
  main/src/main/java/org/sopt/makers/crew/main/entity/meeting/Meeting.java
  main/src/main/java/org/sopt/makers/crew/main/entity/tag/Tag.java
  main/src/main/java/org/sopt/makers/crew/main/entity/tag/TagType.java
Labels: 🎁 feature, size/L

#528 fix: 커스텀 getter 추가
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/response/MeetingV2GetMeetingByIdResponseDto.java
Labels: 🐞 fix, size/XS

#529 v2.4.0
  deploy-dev.sh
  deploy-prod.sh
  docker-compose.dev.yml
  docker-compose.local.yml
  docker-compose.prod.yml
  docker-compose.yml
  main/src/main/java/org/sopt/makers/crew/main/entity/lightning/Lightning.java
  main/src/main/java/org/sopt/makers/crew/main/entity/lightning/LightningPlaceType.java
  main/src/main/java/org/sopt/makers/crew/main/entity/meeting/Meeting.java
  main/src/main/java/org/sopt/makers/crew/main/entity/meeting/MeetingSearchRepository.java
  main/src/main/java/org/sopt/makers/crew/main/entity/meeting/MeetingSearchRepositoryImpl.java
  main/src/main/java/org/sopt/makers/crew/main/entity/tag/Tag.java
  main/src/main/java/org/sopt/makers/crew/main/entity/tag/TagType.java
  main/src/main/java/org/sopt/makers/crew/main/global/config/CrewDatabaseConfig.java
  main/src/main/java/org/sopt/makers/crew/main/global/jwt/JwtTokenProvider.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/MeetingV2Api.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/MeetingV2Controller.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/response/MeetingV2GetMeetingByIdResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/response/MeetingV2GetRecommendDto.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2Service.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceImpl.java
  main/src/main/resources/application-local.yml
Labels: size/XL, 🚀 deployment, 2️⃣ minor

#531 feat: 번쩍 개설 기능 구현
  main/src/main/java/org/sopt/makers/crew/main/entity/lightning/Lightning.java
  main/src/main/java/org/sopt/makers/crew/main/entity/lightning/LightningPlaceType.java
  main/src/main/java/org/sopt/makers/crew/main/entity/lightning/LightningRepository.java
  main/src/main/java/org/sopt/makers/crew/main/entity/lightning/converter/LightningPlaceTypeConverter.java
  main/src/main/java/org/sopt/makers/crew/main/entity/lightning/converter/LightningTimingTypeConverter.java
  main/src/main/java/org/sopt/makers/crew/main/entity/lightning/enums/LightningPlaceType.java
  main/src/main/java/org/sopt/makers/crew/main/entity/lightning/enums/LightningTimingType.java
  main/src/main/java/org/sopt/makers/crew/main/entity/meeting/Meeting.java
  main/src/main/java/org/sopt/makers/crew/main/entity/tag/Tag.java
  main/src/main/java/org/sopt/makers/crew/main/entity/tag/TagRepository.java
  main/src/main/java/org/sopt/makers/crew/main/entity/tag/TagType.java
  main/src/main/java/org/sopt/makers/crew/main/entity/tag/enums/TagType.java
  main/src/main/java/org/sopt/makers/crew/main/entity/tag/enums/WelcomeMessageType.java
  main/src/main/java/org/sopt/makers/crew/main/entity/tag/enums/WelcomeTypeConverter.java
  main/src/main/java/org/sopt/makers/crew/main/lightning/v2/LightningV2Api.java
  main/src/main/java/org/sopt/makers/crew/main/lightning/v2/LightningV2Controller.java
  main/src/main/java/org/sopt/makers/crew/main/lightning/v2/dto/mapper/LightningMapper.java
  main/src/main/java/org/sopt/makers/crew/main/lightning/v2/dto/request/LightningV2CreateLightningBodyDto.java
  main/src/main/java/org/sopt/makers/crew/main/lightning/v2/dto/request/LightningV2CreateLightningBodyWithoutWelcomeMessageDto.java
  main/src/main/java/org/sopt/makers/crew/main/lightning/v2/dto/response/LightningV2CreateLightningResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/lightning/v2/service/LightningV2Service.java
  main/src/main/java/org/sopt/makers/crew/main/lightning/v2/service/LightningV2ServiceImpl.java
  main/src/main/java/org/sopt/makers/crew/main/tag/v2/dto/response/TagV2CreateTagResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/tag/v2/service/TagV2Service.java
  main/src/main/java/org/sopt/makers/crew/main/tag/v2/service/TagV2ServiceImpl.java
  main/src/main/java/org/sopt/makers/crew/main/user/v2/UserV2Controller.java
Labels: 🎁 feature, size/XL

#535 feat: 번쩍 엔티티에 startDate, endDate 필드 추가 및 기획 변경 싱크 맞추기
  main/src/main/java/org/sopt/makers/crew/main/entity/lightning/Lightning.java
  main/src/main/java/org/sopt/makers/crew/main/entity/lightning/enums/LightningTimingType.java
  main/src/main/java/org/sopt/makers/crew/main/lightning/v2/LightningV2Api.java
  main/src/main/java/org/sopt/makers/crew/main/lightning/v2/LightningV2Controller.java
  main/src/main/java/org/sopt/makers/crew/main/lightning/v2/dto/mapper/LightningMapper.java
  main/src/main/java/org/sopt/makers/crew/main/lightning/v2/dto/request/LightningV2CreateLightningBodyWithoutWelcomeMessageDto.java
  main/src/main/java/org/sopt/makers/crew/main/lightning/v2/service/LightningV2ServiceImpl.java
Labels: 🎁 feature, size/M

#537 refactor: ExceptionHandler 예외 메시지 구체화 및 번쩍 관련 로직 수정
  main/src/main/java/org/sopt/makers/crew/main/global/advice/ControllerExceptionAdvice.java
  main/src/main/java/org/sopt/makers/crew/main/global/exception/BaseException.java
  main/src/main/java/org/sopt/makers/crew/main/global/exception/ErrorStatus.java
  main/src/main/java/org/sopt/makers/crew/main/global/exception/ExceptionResponse.java
  main/src/main/java/org/sopt/makers/crew/main/lightning/v2/dto/request/LightningV2CreateLightningBodyDto.java
  main/src/main/java/org/sopt/makers/crew/main/lightning/v2/dto/request/LightningV2CreateLightningBodyWithoutWelcomeMessageDto.java
Labels: 🛠️ refactor, size/L

#538 refactor: 번쩍 모임 생성 시 모임 정보를 먼저 저장하도록 변경 완료
  main/src/main/java/org/sopt/makers/crew/main/entity/lightning/Lightning.java
  main/src/main/java/org/sopt/makers/crew/main/entity/meeting/Meeting.java
  main/src/main/java/org/sopt/makers/crew/main/global/config/ImageSetting.java
  main/src/main/java/org/sopt/makers/crew/main/global/config/ImageSettingConfig.java
  main/src/main/java/org/sopt/makers/crew/main/global/exception/ErrorStatus.java
  main/src/main/java/org/sopt/makers/crew/main/lightning/v2/dto/mapper/LightningMapper.java
  main/src/main/java/org/sopt/makers/crew/main/lightning/v2/service/LightningV2ServiceImpl.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/response/MeetingV2CreateMeetingForLightningResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2Service.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceImpl.java
  main/src/main/resources/application-dev.yml
  main/src/main/resources/application-local.yml
  main/src/main/resources/application-prod.yml
  main/src/main/resources/application-test.yml
Labels: 🛠️ refactor, size/L

#540 feat: 번쩍 상세 조회 GET API 구현 완료
  main/src/main/java/org/sopt/makers/crew/main/entity/lightning/Lightning.java
  main/src/main/java/org/sopt/makers/crew/main/entity/lightning/LightningRepository.java
  main/src/main/java/org/sopt/makers/crew/main/entity/tag/TagRepository.java
  main/src/main/java/org/sopt/makers/crew/main/global/exception/ErrorStatus.java
  main/src/main/java/org/sopt/makers/crew/main/lightning/v2/LightningV2Api.java
  main/src/main/java/org/sopt/makers/crew/main/lightning/v2/LightningV2Controller.java
  main/src/main/java/org/sopt/makers/crew/main/lightning/v2/dto/response/LightningV2CreateLightningResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/lightning/v2/dto/response/LightningV2GetLightningByMeetingIdResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/lightning/v2/service/LightningV2Service.java
  main/src/main/java/org/sopt/makers/crew/main/lightning/v2/service/LightningV2ServiceImpl.java
  main/src/main/java/org/sopt/makers/crew/main/tag/v2/service/TagV2Service.java
  main/src/main/java/org/sopt/makers/crew/main/tag/v2/service/TagV2ServiceImpl.java
Labels: 🎁 feature, size/L

#542 refactor: 환영 메시지 태그 파싱 로직 단순화
  main/src/main/java/org/sopt/makers/crew/main/entity/tag/Tag.java
  main/src/main/java/org/sopt/makers/crew/main/entity/tag/TagRepository.java
  main/src/main/java/org/sopt/makers/crew/main/entity/tag/WelcomeMessageTypeProjection.java
  main/src/main/java/org/sopt/makers/crew/main/entity/tag/enums/WelcomeTypeConverter.java
  main/src/main/java/org/sopt/makers/crew/main/tag/v2/service/TagV2ServiceImpl.java
Labels: 🛠️ refactor, size/L

#544 chore: 번쩍 도메인 네이밍 lightning -> flash로 변경
  main/src/main/java/org/sopt/makers/crew/main/entity/flash/Flash.java
  main/src/main/java/org/sopt/makers/crew/main/entity/flash/FlashRepository.java
  main/src/main/java/org/sopt/makers/crew/main/entity/flash/converter/FlashPlaceTypeConverter.java
  main/src/main/java/org/sopt/makers/crew/main/entity/flash/converter/FlashTimingTypeConverter.java
  main/src/main/java/org/sopt/makers/crew/main/entity/flash/enums/FlashPlaceType.java
  main/src/main/java/org/sopt/makers/crew/main/entity/flash/enums/FlashTimingType.java
  main/src/main/java/org/sopt/makers/crew/main/entity/lightning/LightningRepository.java
  main/src/main/java/org/sopt/makers/crew/main/entity/lightning/converter/LightningPlaceTypeConverter.java
  main/src/main/java/org/sopt/makers/crew/main/entity/lightning/converter/LightningTimingTypeConverter.java
  main/src/main/java/org/sopt/makers/crew/main/entity/lightning/enums/LightningPlaceType.java
  main/src/main/java/org/sopt/makers/crew/main/entity/lightning/enums/LightningTimingType.java
  main/src/main/java/org/sopt/makers/crew/main/entity/meeting/Meeting.java
  main/src/main/java/org/sopt/makers/crew/main/entity/meeting/enums/MeetingCategory.java
  main/src/main/java/org/sopt/makers/crew/main/entity/tag/Tag.java
  main/src/main/java/org/sopt/makers/crew/main/entity/tag/TagRepository.java
  main/src/main/java/org/sopt/makers/crew/main/entity/tag/enums/TagType.java
  main/src/main/java/org/sopt/makers/crew/main/flash/v2/FlashV2Api.java
  main/src/main/java/org/sopt/makers/crew/main/flash/v2/FlashV2Controller.java
  main/src/main/java/org/sopt/makers/crew/main/flash/v2/dto/mapper/FlashMapper.java
  main/src/main/java/org/sopt/makers/crew/main/flash/v2/dto/request/FlashV2CreateFlashBodyDto.java
  main/src/main/java/org/sopt/makers/crew/main/flash/v2/dto/request/FlashV2CreateFlashBodyWithoutWelcomeMessageDto.java
  main/src/main/java/org/sopt/makers/crew/main/flash/v2/dto/response/FlashV2CreateFlashResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/flash/v2/dto/response/FlashV2GetFlashByMeetingIdResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/flash/v2/service/FlashV2Service.java
  main/src/main/java/org/sopt/makers/crew/main/flash/v2/service/FlashV2ServiceImpl.java
  main/src/main/java/org/sopt/makers/crew/main/global/config/ImageSetting.java
  main/src/main/java/org/sopt/makers/crew/main/global/config/ImageSettingConfig.java
  main/src/main/java/org/sopt/makers/crew/main/global/exception/ErrorStatus.java
  main/src/main/java/org/sopt/makers/crew/main/lightning/v2/LightningV2Controller.java
  main/src/main/java/org/sopt/makers/crew/main/lightning/v2/dto/mapper/LightningMapper.java
  main/src/main/java/org/sopt/makers/crew/main/lightning/v2/dto/response/LightningV2CreateLightningResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/lightning/v2/service/LightningV2Service.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/response/MeetingV2CreateMeetingForFlashResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2Service.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceImpl.java
  main/src/main/java/org/sopt/makers/crew/main/tag/v2/dto/response/TagV2CreateFlashTagResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/tag/v2/dto/response/TagV2CreateTagResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/tag/v2/service/TagV2Service.java
  main/src/main/java/org/sopt/makers/crew/main/tag/v2/service/TagV2ServiceImpl.java
  main/src/main/resources/application-dev.yml
  main/src/main/resources/application-local.yml
  main/src/main/resources/application-prod.yml
  main/src/main/resources/application-test.yml
Labels: size/XL, 🪛 chore

#546 hotfix: 레디스 Host 수정
  main/src/main/resources/application-dev.yml
Labels: 🐞 fix, size/XS

#547 v2.5.0
  main/src/main/java/org/sopt/makers/crew/main/entity/flash/Flash.java
  main/src/main/java/org/sopt/makers/crew/main/entity/flash/FlashRepository.java
  main/src/main/java/org/sopt/makers/crew/main/entity/flash/converter/FlashPlaceTypeConverter.java
  main/src/main/java/org/sopt/makers/crew/main/entity/flash/converter/FlashTimingTypeConverter.java
  main/src/main/java/org/sopt/makers/crew/main/entity/flash/enums/FlashPlaceType.java
  main/src/main/java/org/sopt/makers/crew/main/entity/flash/enums/FlashTimingType.java
  main/src/main/java/org/sopt/makers/crew/main/entity/lightning/Lightning.java
  main/src/main/java/org/sopt/makers/crew/main/entity/lightning/LightningPlaceType.java
  main/src/main/java/org/sopt/makers/crew/main/entity/meeting/Meeting.java
  main/src/main/java/org/sopt/makers/crew/main/entity/meeting/enums/MeetingCategory.java
  main/src/main/java/org/sopt/makers/crew/main/entity/tag/Tag.java
  main/src/main/java/org/sopt/makers/crew/main/entity/tag/TagRepository.java
  main/src/main/java/org/sopt/makers/crew/main/entity/tag/TagType.java
  main/src/main/java/org/sopt/makers/crew/main/entity/tag/WelcomeMessageTypeProjection.java
  main/src/main/java/org/sopt/makers/crew/main/entity/tag/enums/TagType.java
  main/src/main/java/org/sopt/makers/crew/main/entity/tag/enums/WelcomeMessageType.java
  main/src/main/java/org/sopt/makers/crew/main/flash/v2/FlashV2Api.java
  main/src/main/java/org/sopt/makers/crew/main/flash/v2/FlashV2Controller.java
  main/src/main/java/org/sopt/makers/crew/main/flash/v2/dto/mapper/FlashMapper.java
  main/src/main/java/org/sopt/makers/crew/main/flash/v2/dto/request/FlashV2CreateFlashBodyDto.java
  main/src/main/java/org/sopt/makers/crew/main/flash/v2/dto/request/FlashV2CreateFlashBodyWithoutWelcomeMessageDto.java
  main/src/main/java/org/sopt/makers/crew/main/flash/v2/dto/response/FlashV2CreateFlashResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/flash/v2/dto/response/FlashV2GetFlashByMeetingIdResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/flash/v2/service/FlashV2Service.java
  main/src/main/java/org/sopt/makers/crew/main/flash/v2/service/FlashV2ServiceImpl.java
  main/src/main/java/org/sopt/makers/crew/main/global/advice/ControllerExceptionAdvice.java
  main/src/main/java/org/sopt/makers/crew/main/global/config/ImageSetting.java
  main/src/main/java/org/sopt/makers/crew/main/global/config/ImageSettingConfig.java
  main/src/main/java/org/sopt/makers/crew/main/global/exception/BaseException.java
  main/src/main/java/org/sopt/makers/crew/main/global/exception/ErrorStatus.java
  main/src/main/java/org/sopt/makers/crew/main/global/exception/ExceptionResponse.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/response/MeetingV2CreateMeetingForFlashResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2Service.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceImpl.java
  main/src/main/java/org/sopt/makers/crew/main/tag/v2/dto/response/TagV2CreateFlashTagResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/tag/v2/service/TagV2Service.java
  main/src/main/java/org/sopt/makers/crew/main/tag/v2/service/TagV2ServiceImpl.java
  main/src/main/java/org/sopt/makers/crew/main/user/v2/UserV2Controller.java
  main/src/main/resources/application-dev.yml
  main/src/main/resources/application-local.yml
  main/src/main/resources/application-prod.yml
  main/src/main/resources/application-test.yml
Labels: size/XXL, 🚀 deployment, 2️⃣ minor

#549 chore(Dockerfile): pinpoint 의존성 제거
  main/Dockerfile
Labels: size/M, 🪛 chore

#552 v2.5.1
  main/Dockerfile
  main/src/main/java/org/sopt/makers/crew/main/entity/tag/TagRepository.java
  main/src/main/java/org/sopt/makers/crew/main/global/sentry/SentryController.java
  main/src/main/java/org/sopt/makers/crew/main/internal/InternalMeetingStatsApi.java
  main/src/main/java/org/sopt/makers/crew/main/internal/InternalMeetingStatsController.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceImpl.java
Labels: size/M, 🚀 deployment, 3️⃣ patch

#560 feat: 가장 빠르게 신청한 모임 N개 조회 API 개발
  main/src/main/java/org/sopt/makers/crew/main/entity/apply/ApplySearchRepository.java
  main/src/main/java/org/sopt/makers/crew/main/entity/apply/ApplySearchRepositoryImpl.java
  main/src/main/java/org/sopt/makers/crew/main/internal/InternalMeetingStatsApi.java
  main/src/main/java/org/sopt/makers/crew/main/internal/InternalMeetingStatsController.java
  main/src/main/java/org/sopt/makers/crew/main/internal/dto/TopFastestAppliedMeetingResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/internal/dto/TopFastestAppliedMeetingsResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/internal/service/InternalMeetingStatsService.java
Labels: 🎁 feature, size/L

#561 v2.5.2
  main/src/main/java/org/sopt/makers/crew/main/entity/apply/ApplySearchRepository.java
  main/src/main/java/org/sopt/makers/crew/main/entity/apply/ApplySearchRepositoryImpl.java
  main/src/main/java/org/sopt/makers/crew/main/internal/InternalMeetingStatsApi.java
  main/src/main/java/org/sopt/makers/crew/main/internal/InternalMeetingStatsController.java
  main/src/main/java/org/sopt/makers/crew/main/internal/dto/TopFastestAppliedMeetingResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/internal/dto/TopFastestAppliedMeetingsResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/internal/service/InternalMeetingStatsService.java
Labels: size/L, 🚀 deployment, 3️⃣ patch

#563 chore: 가장 빠르게 신청한 모임 수정
  main/src/main/java/org/sopt/makers/crew/main/entity/apply/ApplySearchRepository.java
  main/src/main/java/org/sopt/makers/crew/main/entity/apply/ApplySearchRepositoryImpl.java
  main/src/main/java/org/sopt/makers/crew/main/internal/InternalMeetingStatsApi.java
  main/src/main/java/org/sopt/makers/crew/main/internal/InternalMeetingStatsController.java
  main/src/main/java/org/sopt/makers/crew/main/internal/service/InternalMeetingStatsService.java
Labels: size/M, 🪛 chore

#564 v2.5.3
  main/src/main/java/org/sopt/makers/crew/main/entity/apply/ApplySearchRepository.java
  main/src/main/java/org/sopt/makers/crew/main/entity/apply/ApplySearchRepositoryImpl.java
  main/src/main/java/org/sopt/makers/crew/main/internal/InternalMeetingStatsApi.java
  main/src/main/java/org/sopt/makers/crew/main/internal/InternalMeetingStatsController.java
  main/src/main/java/org/sopt/makers/crew/main/internal/service/InternalMeetingStatsService.java
Labels: size/M, 🚀 deployment, 3️⃣ patch
