Repository sopt-makers/sopt-crew-backend, pull requests merged in 2025-06, with the labels that each got.

#683 fix: 유저 키워드 post 전송시 문제가 되었던 수정, get을 통한 키워드 조회 진행할 수 있도록 변경
  main/src/main/java/org/sopt/makers/crew/main/entity/user/User.java
  main/src/main/java/org/sopt/makers/crew/main/entity/user/UserReader.java
  main/src/main/java/org/sopt/makers/crew/main/entity/user/UserRepository.java
  main/src/main/java/org/sopt/makers/crew/main/entity/user/projection/UserKeywordsProjection.java
  main/src/main/java/org/sopt/makers/crew/main/user/v2/UserV2Api.java
  main/src/main/java/org/sopt/makers/crew/main/user/v2/UserV2Controller.java
  main/src/main/java/org/sopt/makers/crew/main/user/v2/dto/UpdateUserInterestKeywordRequestDto.java
  main/src/main/java/org/sopt/makers/crew/main/user/v2/dto/response/UserV2GetInterestedKeywordsResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/user/v2/service/UserV2Service.java
  main/src/main/java/org/sopt/makers/crew/main/user/v2/service/UserV2ServiceImpl.java
  main/src/test/java/org/sopt/makers/crew/main/user/v2/UserServiceTest.java
Labels: 🐞 fix, 🎁 feature, size/L

#684 v2.8.1
  main/src/main/java/org/sopt/makers/crew/main/entity/user/User.java
  main/src/main/java/org/sopt/makers/crew/main/entity/user/UserReader.java
  main/src/main/java/org/sopt/makers/crew/main/entity/user/UserRepository.java
  main/src/main/java/org/sopt/makers/crew/main/entity/user/projection/UserKeywordsProjection.java
  main/src/main/java/org/sopt/makers/crew/main/user/v2/UserV2Api.java
  main/src/main/java/org/sopt/makers/crew/main/user/v2/UserV2Controller.java
  main/src/main/java/org/sopt/makers/crew/main/user/v2/dto/UpdateUserInterestKeywordRequestDto.java
  main/src/main/java/org/sopt/makers/crew/main/user/v2/dto/response/UserV2GetInterestedKeywordsResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/user/v2/service/UserV2Service.java
  main/src/main/java/org/sopt/makers/crew/main/user/v2/service/UserV2ServiceImpl.java
  main/src/test/java/org/sopt/makers/crew/main/user/v2/UserServiceTest.java
Labels: size/L, 🚀 deployment, 3️⃣ patch

#686 chore: 일반 모임 삭제 후 존재하지 않는 meetingId로 조회 시 404 에러를 반환하도록 변경 완료
  main/src/main/java/org/sopt/makers/crew/main/entity/meeting/MeetingRepository.java
Labels: size/XS, 🪛 chore

#687 v2.8.2
  main/src/main/java/org/sopt/makers/crew/main/entity/meeting/MeetingRepository.java
Labels: size/XS, 🚀 deployment, 🪛 chore, 3️⃣ patch

#689 refactor: 번쩍 생성 시 알림 보내는 기존 로직 제거하고 키워드 알림 로직을 사용하도록 변경 완료
  main/src/main/java/org/sopt/makers/crew/main/external/notification/dto/event/FlashCreatedEventDto.java
  main/src/main/java/org/sopt/makers/crew/main/external/notification/event/FlashCreatedEventListener.java
  main/src/main/java/org/sopt/makers/crew/main/flash/v2/service/FlashV2ServiceImpl.java
Labels: 🛠️ refactor, size/M

#695 feat: 플그를 위한 좋아요 동기화 API 구현
  main/src/main/java/org/sopt/makers/crew/main/entity/like/LikeRepository.java
  main/src/main/java/org/sopt/makers/crew/main/internal/InternalMeetingStatsApi.java
  main/src/main/java/org/sopt/makers/crew/main/internal/InternalMeetingStatsController.java
  main/src/main/java/org/sopt/makers/crew/main/internal/dto/InternalPostLikeRequestDto.java
  main/src/main/java/org/sopt/makers/crew/main/internal/dto/InternalPostLikeResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/internal/service/InternalMeetingStatsService.java
Labels: 🎁 feature, size/L

#696 feat : 플크루 협업 작업을 위한 api 중 get 메서드 작업 진행
  main/src/main/java/org/sopt/makers/crew/main/entity/meeting/MeetingSearchRepository.java
  main/src/main/java/org/sopt/makers/crew/main/entity/meeting/MeetingSearchRepositoryImpl.java
  main/src/main/java/org/sopt/makers/crew/main/internal/InternalMeetingApi.java
  main/src/main/java/org/sopt/makers/crew/main/internal/InternalMeetingController.java
  main/src/main/java/org/sopt/makers/crew/main/internal/dto/InternalMeetingForWritingPostDto.java
  main/src/main/java/org/sopt/makers/crew/main/internal/dto/InternalMeetingGetAllWritingPostResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/internal/service/InternalMeetingService.java
Labels: size/L
