Repository sopt-makers/sopt-crew-backend, pull requests merged in 2025-03, with the labels that each got.

#579 feat: 특정 기수 모임 개수 반환 (for 공홈 BE)
  main/src/main/java/org/sopt/makers/crew/main/entity/meeting/MeetingRepository.java
  main/src/main/java/org/sopt/makers/crew/main/internal/InternalMeetingStatsApi.java
  main/src/main/java/org/sopt/makers/crew/main/internal/InternalMeetingStatsController.java
  main/src/main/java/org/sopt/makers/crew/main/internal/dto/InternalMeetingCountResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/internal/service/InternalMeetingStatsService.java
Labels: 🎁 feature, size/M

#582 fix: targetDesc 오류 해결
  main/src/main/java/org/sopt/makers/crew/main/entity/meeting/Meeting.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/redis/MeetingRedisDto.java
  main/src/test/java/org/sopt/makers/crew/main/comment/v2/service/CommentV2ServiceTest.java
  main/src/test/java/org/sopt/makers/crew/main/entity/apply/AppliesTest.java
  main/src/test/java/org/sopt/makers/crew/main/entity/meeting/MeetingTest.java
  main/src/test/java/org/sopt/makers/crew/main/post/v2/service/PostV2ServiceTest.java
Labels: 🐞 fix, size/S

#583 v2.5.5
  main/.gitignore
  main/src/main/java/org/sopt/makers/crew/main/entity/meeting/Meeting.java
  main/src/main/java/org/sopt/makers/crew/main/entity/meeting/MeetingRepository.java
  main/src/main/java/org/sopt/makers/crew/main/entity/meeting/MeetingSearchRepositoryImpl.java
  main/src/main/java/org/sopt/makers/crew/main/global/pagination/AdvertisementPageableStrategy.java
  main/src/main/java/org/sopt/makers/crew/main/global/pagination/DefaultPageableStrategy.java
  main/src/main/java/org/sopt/makers/crew/main/global/pagination/PageableStrategy.java
  main/src/main/java/org/sopt/makers/crew/main/global/pagination/PaginationType.java
  main/src/main/java/org/sopt/makers/crew/main/internal/InternalMeetingStatsApi.java
  main/src/main/java/org/sopt/makers/crew/main/internal/InternalMeetingStatsController.java
  main/src/main/java/org/sopt/makers/crew/main/internal/dto/InternalMeetingCountResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/internal/service/InternalMeetingStatsService.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/MeetingV2Api.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/query/MeetingV2GetAllMeetingQueryDto.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/redis/MeetingRedisDto.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceImpl.java
  main/src/test/java/org/sopt/makers/crew/main/comment/v2/service/CommentV2ServiceTest.java
  main/src/test/java/org/sopt/makers/crew/main/entity/apply/AppliesTest.java
  main/src/test/java/org/sopt/makers/crew/main/entity/meeting/MeetingTest.java
  main/src/test/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceTest.java
  main/src/test/java/org/sopt/makers/crew/main/post/v2/service/PostV2ServiceTest.java
Labels: size/L, 🚀 deployment, 3️⃣ patch

#577 feat: 번쩍 개설 시 Push 알림 기능 구현 완료
  main/build.gradle
  main/src/main/java/org/sopt/makers/crew/main/MainApplication.java
  main/src/main/java/org/sopt/makers/crew/main/auth/v2/service/AuthV2ServiceImpl.java
  main/src/main/java/org/sopt/makers/crew/main/comment/v2/service/CommentV2ServiceImpl.java
  main/src/main/java/org/sopt/makers/crew/main/entity/user/UserReader.java
  main/src/main/java/org/sopt/makers/crew/main/entity/user/UserRepository.java
  main/src/main/java/org/sopt/makers/crew/main/external/notification/PushNotificationEnums.java
  main/src/main/java/org/sopt/makers/crew/main/external/notification/PushNotificationServerClient.java
  main/src/main/java/org/sopt/makers/crew/main/external/notification/PushNotificationService.java
  main/src/main/java/org/sopt/makers/crew/main/flash/v2/service/FlashV2ServiceImpl.java
  main/src/main/java/org/sopt/makers/crew/main/global/config/ImageSetting.java
  main/src/main/java/org/sopt/makers/crew/main/global/config/ImageSettingConfig.java
  main/src/main/java/org/sopt/makers/crew/main/global/config/ImageSettingProperties.java
  main/src/main/java/org/sopt/makers/crew/main/global/config/PushNotificationProperties.java
  main/src/main/java/org/sopt/makers/crew/main/global/dto/OrgIdListDto.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceImpl.java
  main/src/main/java/org/sopt/makers/crew/main/post/v2/service/PostV2ServiceImpl.java
Labels: 🎁 feature, size/L

#585 refactor: EventListener와 비동기 알림 서버 요청을 통한 번쩍 개설 응답속도 개선
  main/src/main/java/org/sopt/makers/crew/main/comment/v2/service/CommentV2ServiceImpl.java
  main/src/main/java/org/sopt/makers/crew/main/external/notification/PushNotificationServerClient.java
  main/src/main/java/org/sopt/makers/crew/main/external/notification/PushNotificationService.java
  main/src/main/java/org/sopt/makers/crew/main/external/notification/dto/PushNotificationRequestDto.java
  main/src/main/java/org/sopt/makers/crew/main/external/notification/dto/PushNotificationResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/external/notification/dto/event/FlashCreatedEventDto.java
  main/src/main/java/org/sopt/makers/crew/main/external/notification/dto/request/PushNotificationRequestDto.java
  main/src/main/java/org/sopt/makers/crew/main/external/notification/dto/response/PushNotificationResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/external/notification/event/FlashCreatedEventListener.java
  main/src/main/java/org/sopt/makers/crew/main/flash/v2/service/FlashV2ServiceImpl.java
  main/src/main/java/org/sopt/makers/crew/main/global/advice/GlobalAsyncExceptionHandler.java
  main/src/main/java/org/sopt/makers/crew/main/global/aop/ExecutionLoggingAop.java
  main/src/main/java/org/sopt/makers/crew/main/global/config/AsyncThreadConfig.java
  main/src/main/java/org/sopt/makers/crew/main/global/config/ThreadPoolProperties.java
  main/src/main/java/org/sopt/makers/crew/main/post/v2/service/PostV2ServiceImpl.java
  main/src/main/resources/application-dev.yml
  main/src/main/resources/application-local.yml
  main/src/main/resources/application-prod.yml
  main/src/main/resources/application-test.yml
Labels: 🛠️ refactor, size/L

#586 v2.5.6
  main/build.gradle
  main/src/main/java/org/sopt/makers/crew/main/MainApplication.java
  main/src/main/java/org/sopt/makers/crew/main/auth/v2/service/AuthV2ServiceImpl.java
  main/src/main/java/org/sopt/makers/crew/main/comment/v2/service/CommentV2ServiceImpl.java
  main/src/main/java/org/sopt/makers/crew/main/entity/user/UserReader.java
  main/src/main/java/org/sopt/makers/crew/main/entity/user/UserRepository.java
  main/src/main/java/org/sopt/makers/crew/main/external/notification/PushNotificationEnums.java
  main/src/main/java/org/sopt/makers/crew/main/external/notification/PushNotificationServerClient.java
  main/src/main/java/org/sopt/makers/crew/main/external/notification/PushNotificationService.java
  main/src/main/java/org/sopt/makers/crew/main/external/notification/dto/PushNotificationRequestDto.java
  main/src/main/java/org/sopt/makers/crew/main/external/notification/dto/PushNotificationResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/external/notification/dto/event/FlashCreatedEventDto.java
  main/src/main/java/org/sopt/makers/crew/main/external/notification/dto/request/PushNotificationRequestDto.java
  main/src/main/java/org/sopt/makers/crew/main/external/notification/dto/response/PushNotificationResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/external/notification/event/FlashCreatedEventListener.java
  main/src/main/java/org/sopt/makers/crew/main/flash/v2/service/FlashV2ServiceImpl.java
  main/src/main/java/org/sopt/makers/crew/main/global/advice/GlobalAsyncExceptionHandler.java
  main/src/main/java/org/sopt/makers/crew/main/global/aop/ExecutionLoggingAop.java
  main/src/main/java/org/sopt/makers/crew/main/global/config/AsyncThreadConfig.java
  main/src/main/java/org/sopt/makers/crew/main/global/config/ImageSetting.java
  main/src/main/java/org/sopt/makers/crew/main/global/config/ImageSettingConfig.java
  main/src/main/java/org/sopt/makers/crew/main/global/config/ImageSettingProperties.java
  main/src/main/java/org/sopt/makers/crew/main/global/config/PushNotificationProperties.java
  main/src/main/java/org/sopt/makers/crew/main/global/config/ThreadPoolProperties.java
  main/src/main/java/org/sopt/makers/crew/main/global/dto/OrgIdListDto.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceImpl.java
  main/src/main/java/org/sopt/makers/crew/main/post/v2/service/PostV2ServiceImpl.java
  main/src/main/resources/application-dev.yml
  main/src/main/resources/application-local.yml
  main/src/main/resources/application-prod.yml
  main/src/main/resources/application-test.yml
Labels: size/XL, 🚀 deployment, 3️⃣ patch

#588 refactor: 최신 기수(36th) 변경에 따른 Crew Const 변경
  main/build.gradle
  main/src/main/java/org/sopt/makers/crew/main/entity/meeting/MeetingSearchRepository.java
  main/src/main/java/org/sopt/makers/crew/main/entity/meeting/MeetingSearchRepositoryImpl.java
  main/src/main/java/org/sopt/makers/crew/main/flash/v2/service/FlashV2ServiceImpl.java
  main/src/main/java/org/sopt/makers/crew/main/global/constant/CrewConst.java
  main/src/main/java/org/sopt/makers/crew/main/global/dto/MeetingResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/global/util/ActiveGenerationProvider.java
  main/src/main/java/org/sopt/makers/crew/main/global/util/DefaultActiveGenerationProvider.java
  main/src/main/java/org/sopt/makers/crew/main/internal/service/InternalMeetingService.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/FlashMeetingMapper.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceImpl.java
  main/src/main/java/org/sopt/makers/crew/main/user/v2/dto/response/MeetingV2GetCreatedMeetingByUserResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/user/v2/service/UserV2ServiceImpl.java
  main/src/test/java/org/sopt/makers/crew/main/global/util/TestActiveGenerationProvider.java
  main/src/test/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceTest.java
Labels: 🛠️ refactor, size/L

#594 feat: 모임 정보에 신청 순서 추가
  main/src/main/java/org/sopt/makers/crew/main/flash/v2/service/FlashV2ServiceImpl.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/response/ApplyInfoDetailDto.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/response/ApplyWholeInfoDto.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/response/MeetingGetApplyListResponseDto.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceImpl.java
  main/src/test/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceTest.java
Labels: 🎁 feature, size/L

#599 feat: Crew 스프링 서버를 Pinpoint Agent와 함께 실행하는 기능 구현
  main/Dockerfile
  main/scripts/entrypoint.sh
Labels: size/M

#601 refactor: Pinpoint Agent 버전 다운그레이드 완료
  main/scripts/entrypoint.sh
Labels: 🛠️ refactor, size/XS

#597 refactor: redis -> 로컬 캐시로 변환
  main/build.gradle
  main/src/main/java/org/sopt/makers/crew/main/entity/meeting/MeetingReader.java
  main/src/main/java/org/sopt/makers/crew/main/external/caffeine/CacheInfo.java
  main/src/main/java/org/sopt/makers/crew/main/external/caffeine/CacheQueryService.java
  main/src/main/java/org/sopt/makers/crew/main/external/caffeine/CachesEndpointExtension.java
  main/src/main/java/org/sopt/makers/crew/main/external/caffeine/CaffeineConfig.java
  main/src/main/java/org/sopt/makers/crew/main/external/redis/RedisConfig.java
  main/src/main/java/org/sopt/makers/crew/main/global/config/SecurityConfig.java
  main/src/main/java/org/sopt/makers/crew/main/meeting/v2/dto/redis/MeetingCacheDto.java
  main/src/main/resources/application-dev.yml
  main/src/test/java/org/sopt/makers/crew/main/external/CaffeineTestConfig.java
  main/src/test/java/org/sopt/makers/crew/main/meeting/v2/service/MeetingV2ServiceTest.java
Labels: size/L

#606 feat: application-traffic.yml 세팅 진행
  main/src/main/resources/application-dev.yml
  main/src/main/resources/application-prod.yml
  main/src/main/resources/application-traffic.yml
Labels: 🎁 feature, size/M

#610 fix: 센트리 환경변수 수정 및 운영환경과 세팅 통일
  main/src/main/resources/application-dev.yml
  main/src/main/resources/application-prod.yml
  main/src/main/resources/application-test.yml
  main/src/main/resources/application-traffic.yml
Labels: 🐞 fix, size/S

#619 fix: traffic 브랜치로 체크아웃 후 스크립트 실행하도록 수정
  .github/workflows/cd-traffic.yml
Labels: 🐞 fix, size/XS
